(function(){
'use strict';var Uf=function(a,b){return $APP.aa[a]=b},Vf=function(a){if(null!=a&&null!=a.xa)a=a.xa(a);else{var b=Vf[$APP.r(null==a?null:a)];if(null!=b)a=b.g?b.g(a):b.call(null,a);else if(b=Vf._,null!=b)a=b.g?b.g(a):b.call(null,a);else throw $APP.y("IStack.-peek",a);}return a},Wf=function(a){if(null!=a&&null!=a.ya)a=a.ya(a);else{var b=Wf[$APP.r(null==a?null:a)];if(null!=b)a=b.g?b.g(a):b.call(null,a);else if(b=Wf._,null!=b)a=b.g?b.g(a):b.call(null,a);else throw $APP.y("IStack.-pop",a);}return a},Xf=
function(){},Yf=function(a){if(null!=a&&null!=a.Wa)a=a.Wa(a);else{var b=Yf[$APP.r(null==a?null:a)];if(null!=b)a=b.g?b.g(a):b.call(null,a);else if(b=Yf._,null!=b)a=b.g?b.g(a):b.call(null,a);else throw $APP.y("IReversible.-rseq",a);}return a},Zf=function(a,b){if(null!=$APP.Qf&&null!=$APP.Qf.Eb)$APP.Qf.Eb($APP.Qf,a,b);else{var c=Zf[$APP.r(null==$APP.Qf?null:$APP.Qf)];if(null!=c)c.i?c.i($APP.Qf,a,b):c.call(null,$APP.Qf,a,b);else if(c=Zf._,null!=c)c.i?c.i($APP.Qf,a,b):c.call(null,$APP.Qf,a,b);else throw $APP.y("IWatchable.-add-watch",
$APP.Qf);}},$f=function(a,b){if(null!=a&&null!=a.ec)a=a.ec(a,b);else{var c=$f[$APP.r(null==a?null:a)];if(null!=c)a=c.h?c.h(a,b):c.call(null,a,b);else if(c=$f._,null!=c)a=c.h?c.h(a,b):c.call(null,a,b);else throw $APP.y("IReset.-reset!",a);}return a},ag=function(a){return a+1},bg=function(a){if(null==$APP.Aa)throw Error("No *print-fn* fn set for evaluation environment");$APP.Aa.call(null,a)},cg=function(a){for(;;)if(a=$APP.F(a))a=$APP.J(a);else break},dg=function(a,b){for(;;)if(b=$APP.F(b)){var c=$APP.G(b);
c=a.g?a.g(c):a.call(null,c);if($APP.v(c))return c;b=$APP.J(b)}else return null},eg=function(a,b,c){return 0<c?b<=a?$APP.H:$APP.xc(a)&&$APP.xc(b)&&$APP.xc(c)?new $APP.Te(null,a,b,c,null,null,null):new $APP.Ue(null,a,b,c,null,null,null):0>c?b>=a?$APP.H:$APP.xc(a)&&$APP.xc(b)&&$APP.xc(c)?new $APP.Te(null,a,b,c,null,null,null):new $APP.Ue(null,a,b,c,null,null,null):b===a?$APP.H:new $APP.sd(null,-1,a,null)},fg=function(a){return eg(0,a,1)},gg=function(a,b){return function(){function c(l,m,n){return a.G?
a.G(b,l,m,n):a.call(null,b,l,m,n)}function d(l,m){return a.i?a.i(b,l,m):a.call(null,b,l,m)}function e(l){return a.h?a.h(b,l):a.call(null,b,l)}function f(){return a.g?a.g(b):a.call(null,b)}var h=null,k=function(){function l(n,p,q,u){var x=null;if(3<arguments.length){x=0;for(var A=Array(arguments.length-3);x<A.length;)A[x]=arguments[x+3],++x;x=new $APP.D(A,0,null)}return m.call(this,n,p,q,x)}function m(n,p,q,u){return $APP.jd(a,b,n,p,q,$APP.R([u]))}l.I=3;l.K=function(n){var p=$APP.G(n);n=$APP.J(n);
var q=$APP.G(n);n=$APP.J(n);var u=$APP.G(n);n=$APP.I(n);return m(p,q,u,n)};l.s=m;return l}();h=function(l,m,n,p){switch(arguments.length){case 0:return f.call(this);case 1:return e.call(this,l);case 2:return d.call(this,l,m);case 3:return c.call(this,l,m,n);default:var q=null;if(3<arguments.length){q=0;for(var u=Array(arguments.length-3);q<u.length;)u[q]=arguments[q+3],++q;q=new $APP.D(u,0,null)}return k.s(l,m,n,q)}throw Error("Invalid arity: "+arguments.length);};h.I=3;h.K=k.K;h.D=f;h.g=e;h.h=d;
h.i=c;h.s=k.s;return h}()},ig=function(a){var b=/([a-z]+)\(([^)]+)\)\s*/;if("string"===typeof a)return hg(b,a);throw new TypeError("re-seq must match against a string.");},jg=function(a,b){return new $APP.Sc(null,function(){a:for(var c=a,d=b;;)if(d=$APP.F(d),0<c&&d)--c,d=$APP.I(d);else break a;return d},null)},kg=function(a,b){return new $APP.Sc(null,function(){if(0<a){var c=$APP.F(b);return c?$APP.V($APP.G(c),kg(a-1,$APP.I(c))):null}return null},null)},lg=function(a){return(null!=a?a.l&134217728||
$APP.C===a.Bc||(a.l?0:$APP.w(Xf,a)):$APP.w(Xf,a))?(a=Yf(a))?a:$APP.H:$APP.Dc($APP.td,$APP.H,a)},mg=function(a){var b=$APP.Z.i($APP.ya(),$APP.ta,!1);bg($APP.kf(a,b));$APP.v($APP.za)?(a=$APP.ya(),bg("\n"),a=($APP.S.h(a,$APP.sa),null)):a=null;return a},ng=function(a,b){if(a instanceof $APP.rd){var c=a.qc;if(null!=c&&!$APP.v(c.g?c.g(b):c.call(null,b)))throw Error("Validator rejected reference state");c=a.state;a.state=b;if(null!=a.yb)a:for(var d=$APP.F(a.yb),e=null,f=0,h=0;;)if(h<f){var k=e.M(null,h),
l=$APP.N.i(k,0,null);k=$APP.N.i(k,1,null);k.G?k.G(l,a,c,b):k.call(null,l,a,c,b);h+=1}else if(d=$APP.F(d))$APP.uc(d)?(e=$APP.xb(d),d=$APP.yb(d),l=e,f=$APP.M(e),e=l):(e=$APP.G(d),l=$APP.N.i(e,0,null),k=$APP.N.i(e,1,null),k.G?k.G(l,a,c,b):k.call(null,l,a,c,b),d=$APP.J(d),e=null,f=0),h=0;else break a;return b}return $f(a,b)},qg=function(a){null==og&&(og=new $APP.rd(0));var b=$APP.lf.g([$APP.z.g("G__"),$APP.z.g(pg.h(og,ag))].join(""));Zf(b,a)},rg=function(a){this.f=a;this.value=null;this.l=2147516416;
this.B=1},sg=function(a){if("string"===typeof a)return $APP.Ve(/[\x00-\x20]*[+-]?NaN[\x00-\x20]*/,a)?NaN:$APP.Ve(/[\x00-\x20]*[+-]?(Infinity|((\d+\.?\d*|\.\d+)([eE][+-]?\d+)?)[dDfF]?)[\x00-\x20]*/,a)?parseFloat(a):null;throw Error(["Expected string, got: ",$APP.z.g(null==a?"nil":$APP.r(a))].join(""));},tg=function(a,b,c){qg(function(d,e,f,h){d=$APP.S.h(f,a);h=$APP.S.h(h,a);return $APP.fc.h(d,h)?null:$APP.hd(b,h,c)})},ug=function(a){for(var b=[],c=arguments.length,d=0;;)if(d<c)b.push(arguments[d]),
d+=1;else break;tg(arguments[0],arguments[1],2<b.length?new $APP.D(b.slice(2),0,null):null)},vg=function(a,b){var c=$APP.F(b);$APP.G(c);c=$APP.J(c);$APP.G(c);for($APP.J(c);;){c=$APP.F(b);b=$APP.G(c);c=$APP.J(c);var d=$APP.G(c);c=$APP.J(c);if($APP.v(b))a[b]=d,b=c;else return a}},wg=function(a,b){var c=$APP.N.i(a,0,null);a=$APP.N.i(a,1,null);var d=$APP.N.i(b,0,null);b=$APP.N.i(b,1,null);var e=a-c,f=b-d;return function(h){return d+(h-c)/e*f}},xg=function(a){return function(b){return 0>b?0:b>a?a:b}},
yg=function(a){return"string"===typeof a?document.getElementById(a):a},zg=function(a){$APP.pf(yg(a),"classList").add("active");return a},Ag=function(a){$APP.pf(yg(a),"classList").remove("active");return a},Bg=function(a,b){a=yg(a);vg(a,$APP.R(["textContent",b]));return a},Cg=function(a,b,c){yg(a).addEventListener($APP.Qe(b),c,null)},Dg=function(a,b){$APP.v($APP.Kf.g($APP.ab($APP.Qf)))&&(a=$APP.N.h($APP.Tf,a),a.stereo(b),a.play())},Eg=function(a){return $APP.v(a)?zg("sound"):Ag("sound")},Fg=function(a){if($APP.v(a))return zg("fullscreen"),
yg("wrapper").requestFullscreen().then(function(){return mg($APP.R(["fullscreen: success"]))},function(){return mg($APP.R(["fullscreen: rejected"]))});Ag("fullscreen");return document.exitFullscreen().then(function(){return mg($APP.R(["fullscreen: success"]))},function(){return mg($APP.R(["fullscreen: rejected"]))})},Kg=function(){var a=null!=$APP.pf(document,"exitFullscreen"),b=null!=$APP.pf(document,"fullscreenElement");if(!a)a:{var c=$APP.R([Gg,"none"]),d=yg("fullscreen"),e=$APP.F(c);$APP.G(e);
e=$APP.J(e);$APP.G(e);for($APP.J(e);;){e=$APP.F(c);c=$APP.G(e);e=$APP.J(e);var f=$APP.G(e);e=$APP.J(e);d.setAttribute($APP.Qe(c),$APP.z.g(f));if($APP.F(e))c=e;else break a}}a&&ug(Hg,Fg);pg.i($APP.Qf,Ig,new $APP.t(null,2,[Jg,a,Hg,b],null))},Lg=function(a){return $APP.v(a)?$APP.Dc(function(b,c){$APP.N.i(c,0,null);var d=$APP.N.i(c,1,null),e=$APP.N.i(c,2,null);c=$APP.Z.i;d=$APP.ef.g(d);var f=$APP.df.h,h=/[\s,]/;e="/(?:)/"===$APP.z.g(h)?$APP.td.h($APP.Kd($APP.V("",$APP.df.h($APP.z,$APP.F(e)))),""):$APP.Kd($APP.z.g(e).split(h));
if(1<$APP.M(e))a:for(;;)if(""===(null==e?null:Vf(e)))e=null==e?null:Wf(e);else break a;return c.call($APP.Z,b,d,f.call($APP.df,sg,e))},$APP.nd,ig(a)):null},Ng=function(a){return $APP.Dc(function(b,c){var d=c.g?c.g(a):c.call(null,a);if($APP.v(d)){b=$APP.z.g(b);c=$APP.Qe(c);var e=$APP.z,f=e.g;if($APP.oc(d))a:{var h=new $APP.ra;for(d=$APP.F(d);;)if(null!=d)h.append($APP.z.g($APP.G(d))),d=$APP.J(d),null!=d&&h.append(" ");else{d=h.toString();break a}}b=[b,c,"(",f.call(e,d),") "].join("")}return b},"",
Mg)},Og=function(a){return $APP.Dc(function(b,c){var d=$APP.qa(a,c);return $APP.v(d)?$APP.Z.i(b,c,d):b},$APP.nd,Mg)},Qg=function(a,b){return $APP.Dc(function(c,d){var e=$APP.N.i(d,0,null);d=$APP.N.i(d,1,null);return $APP.fc.h(e,Pg)?Lg(d):$APP.Z.i(c,e,d)},Og(a),b)},Rg=function(a,b){b=$APP.F(b);for(var c=null,d=0,e=0;;)if(e<d){var f=c.M(null,e);a.appendChild(f);e+=1}else if(b=$APP.F(b))c=b,$APP.uc(c)?(b=$APP.xb(c),e=$APP.yb(c),c=b,d=$APP.M(b),b=e):(b=$APP.G(c),a.appendChild(b),b=$APP.J(c),c=null,d=
0),e=0;else break;return a},Sg=function(a,b){return Rg(a,b)},Xg=function(a,b,c,d){return Tg.s("circle",$APP.R([$APP.Z.s(a,Ug,b,$APP.R([Vg,c,Wg,d]))]))},bh=function(a,b,c,d){return Tg.s("line",$APP.R([$APP.Z.s(null,Yg,a,$APP.R([Zg,b,$g,c,ah,d]))]))},dh=function(a,b){return Tg.s("polyline",$APP.R([$APP.Z.i(a,ch,$APP.Dc(function(c,d){var e=$APP.N.i(d,0,null);d=$APP.N.i(d,1,null);return[$APP.z.g(c),$APP.z.g(e),",",$APP.z.g(d)," "].join("")},"",b))]))},jh=function(a){var b=100+1E3/(eh+2)*a,c=180*(20+.5*
a)/3E5;return vg(fh(Xg(new $APP.t(null,1,[gh,["hsl(",$APP.z.g(hh(a))," 100% 50%)"].join("")],null),b,0,15)),$APP.R([ih,c]))},mh=function(a){var b=100+1E3/(eh+2)*a;a=new $APP.t(null,1,[kh,"hsl(0 0% 30%)"],null);b=["M 0,",$APP.z.g(-b)," A ",$APP.z.g(b)," ",$APP.z.g(b)," 180 1 1 0,",$APP.z.g(b)].join("");return Tg.s("path",$APP.R([$APP.Z.i(a,lh,b)]))},sh=function(a,b,c){var d=nh(a);a=oh(a);b=b*ph+c*a;return new $APP.X(null,2,5,$APP.Y,[d*(qh.g?qh.g(b):qh.call(null,b)),d*(rh.g?rh.g(b):rh.call(null,b))],
null)},Ah=function(a){console.log("swap-scene:",a);var b=$APP.N.h(th,a);var c=uh.g(b);c=c.D?c.D():c.call(null);ng(vh,a);ng(wh,c);Bg("scene-name",xh.g(b));a=Bg("app","");var d=$APP.R([yh.g(c)]);a=yg(a);d=$APP.F(d);for(var e=null,f=0,h=0;;)if(h<f){var k=e.M(null,h);a.append(k);h+=1}else if(d=$APP.F(d))e=d,$APP.uc(e)?(d=$APP.xb(e),h=$APP.yb(e),e=d,f=$APP.M(d),d=h):(d=$APP.G(e),a.append(d),d=$APP.J(e),e=null,f=0),h=0;else break;a=zh.g(b);a.h?a.h(c,null):a.call(null,c,null);vg(location,$APP.R(["hash",
xh.g(b)]));return localStorage.setItem("scene-name",xh.g(b))},Bh=function(a){var b=$APP.ab(vh);b=$APP.N.h(th,b);return pg.i(wh,zh.g(b),a)},Eh=function(){Cg(window,Ch,Bh);ug(Dh,Ah);var a=function(){var c=location.hash;c=$APP.na(null==c?"":String(c))?null:c.substring(1);$APP.v(c)||(c=localStorage.getItem("scene-name"),c=$APP.na(null==c?"":String(c))?null:c);return c}(),b=$APP.v(a)?dg(function(c){return $APP.fc.h(xh.g($APP.N.h(th,c)),a)?c:null},fg($APP.M(th))):0;pg.G($APP.Qf,$APP.Z,Dh,b)},Gh=function(){return pg.G($APP.Qf,
Fh,$APP.Kf,$APP.Da)},Hh=function(){return pg.G($APP.Qf,Fh,Hg,$APP.Da)},Ih=function(a){return function(){return pg.s($APP.Qf,Fh,Dh,function(b,c){b+=c;return b>=$APP.M(th)?0:0>b?$APP.M(th)-1:b},$APP.R([a]))}},Mh=function(a){var b=function(){switch($APP.pf(a,Jh)){case "ArrowUp":return Hh;case "ArrowRight":return Kh;case "ArrowLeft":return Lh;case "ArrowDown":return Gh;default:return null}}();$APP.v(b)&&(a.preventDefault(),b.D?b.D():b.call(null));return null},Oh=function(){return $APP.ab(Nh)},Ph=function Ph(a,
b,c){var e=a.m-2>>>b&31;if(5<b){b-=5;var f=c.j[e];a=Ph.i?Ph.i(a,b,f):Ph.call(null,a,b,f);if(null==a&&0===e)return null;c=$APP.zd(c);c.j[e]=a;return c}if(0===e)return null;c=$APP.zd(c);c.j[e]=null;return c};$APP.rd.prototype.Eb=Uf(11,function(a,b,c){this.yb=$APP.Z.i(this.yb,b,c);return this});$APP.Oc.prototype.ya=Uf(10,function(){return this.ea(null)});$APP.Pc.prototype.ya=Uf(9,function(){throw Error("Can't pop empty list");});
$APP.X.prototype.ya=Uf(8,function(){if(0===this.m)throw Error("Can't pop empty vector");if(1===this.m)return $APP.db($APP.vd,this.u);if(1<this.m-$APP.Ad(this))return new $APP.X(this.u,this.m-1,this.shift,this.root,this.ja.slice(0,-1),null);var a=$APP.Cd(this,this.m-2),b=Ph(this,this.shift,this.root);b=null==b?$APP.Y:b;var c=this.m-1;return 5<this.shift&&null==b.j[1]?new $APP.X(this.u,c,this.shift-5,b.j[0],a,null):new $APP.X(this.u,c,this.shift,b,a,null)});
$APP.$d.prototype.ya=Uf(7,function(){return new $APP.X(null,1,5,$APP.Y,[this.key],null)});$APP.Oc.prototype.xa=Uf(6,function(){return this.first});$APP.Pc.prototype.xa=Uf(5,function(){return null});$APP.X.prototype.xa=Uf(4,function(){return 0<this.m?this.M(null,this.m-1):null});$APP.$d.prototype.xa=Uf(3,function(){return this.C});$APP.D.prototype.Wa=Uf(2,function(){var a=this.S(null);return 0<a?new $APP.hc(this,a-1,null):null});
$APP.X.prototype.Wa=Uf(1,function(){return 0<this.m?new $APP.hc(this,this.m-1,null):null});$APP.$d.prototype.Wa=Uf(0,function(){return new $APP.D([this.C,this.key],0,null)});var Ig=function Ig(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return Ig.s(0<c.length?new $APP.D(c.slice(0),0,null):null)};Ig.s=function(a){return $APP.v(dg($APP.Kc,a))?$APP.Hc(function(b,c){return $APP.td.h($APP.v(b)?b:$APP.nd,c)},a):null};Ig.I=0;Ig.K=function(a){return this.s($APP.F(a))};
var Fh=function Fh(a){switch(arguments.length){case 3:return Fh.i(arguments[0],arguments[1],arguments[2]);case 4:return Fh.G(arguments[0],arguments[1],arguments[2],arguments[3]);case 5:return Fh.ha(arguments[0],arguments[1],arguments[2],arguments[3],arguments[4]);case 6:return Fh.wa(arguments[0],arguments[1],arguments[2],arguments[3],arguments[4],arguments[5]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return Fh.s(arguments[0],arguments[1],arguments[2],
arguments[3],arguments[4],arguments[5],new $APP.D(c.slice(6),0,null))}};Fh.i=function(a,b,c){var d=$APP.Z.i,e=$APP.S.h(a,b);c=c.g?c.g(e):c.call(null,e);return d.call($APP.Z,a,b,c)};Fh.G=function(a,b,c,d){var e=$APP.Z.i,f=$APP.S.h(a,b);c=c.h?c.h(f,d):c.call(null,f,d);return e.call($APP.Z,a,b,c)};Fh.ha=function(a,b,c,d,e){var f=$APP.Z.i,h=$APP.S.h(a,b);c=c.i?c.i(h,d,e):c.call(null,h,d,e);return f.call($APP.Z,a,b,c)};
Fh.wa=function(a,b,c,d,e,f){var h=$APP.Z.i,k=$APP.S.h(a,b);c=c.G?c.G(k,d,e,f):c.call(null,k,d,e,f);return h.call($APP.Z,a,b,c)};Fh.s=function(a,b,c,d,e,f,h){return $APP.Z.i(a,b,$APP.jd(c,$APP.S.h(a,b),d,e,f,$APP.R([h])))};Fh.K=function(a){var b=$APP.G(a),c=$APP.J(a);a=$APP.G(c);var d=$APP.J(c);c=$APP.G(d);var e=$APP.J(d);d=$APP.G(e);var f=$APP.J(e);e=$APP.G(f);var h=$APP.J(f);f=$APP.G(h);h=$APP.J(h);return this.s(b,a,c,d,e,f,h)};Fh.I=6;
var hg=function hg(a,b){var d=a.exec(b);if(null==d)return null;var e=d[0],f=1===d.length?e:$APP.Kd(d);return $APP.V(f,new $APP.Sc(null,function(){var h=e.length;h=d.index+(1>h?1:h);return h<=b.length?(h=b.substring(h),hg.h?hg.h(a,h):hg.call(null,a,h)):null},null))},Qh=function Qh(a){switch(arguments.length){case 0:return Qh.D();case 1:return Qh.g(arguments[0]);case 2:return Qh.h(arguments[0],arguments[1]);case 3:return Qh.i(arguments[0],arguments[1],arguments[2]);default:for(var c=[],d=arguments.length,
e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return Qh.s(arguments[0],arguments[1],arguments[2],new $APP.D(c.slice(3),0,null))}};Qh.D=function(){return $APP.Kc};Qh.g=function(a){return a};
Qh.h=function(a,b){return function(){function c(l,m,n){l=b.i?b.i(l,m,n):b.call(null,l,m,n);return a.g?a.g(l):a.call(null,l)}function d(l,m){l=b.h?b.h(l,m):b.call(null,l,m);return a.g?a.g(l):a.call(null,l)}function e(l){l=b.g?b.g(l):b.call(null,l);return a.g?a.g(l):a.call(null,l)}function f(){var l=b.D?b.D():b.call(null);return a.g?a.g(l):a.call(null,l)}var h=null,k=function(){function l(n,p,q,u){var x=null;if(3<arguments.length){x=0;for(var A=Array(arguments.length-3);x<A.length;)A[x]=arguments[x+
3],++x;x=new $APP.D(A,0,null)}return m.call(this,n,p,q,x)}function m(n,p,q,u){n=$APP.id(b,n,p,q,u);return a.g?a.g(n):a.call(null,n)}l.I=3;l.K=function(n){var p=$APP.G(n);n=$APP.J(n);var q=$APP.G(n);n=$APP.J(n);var u=$APP.G(n);n=$APP.I(n);return m(p,q,u,n)};l.s=m;return l}();h=function(l,m,n,p){switch(arguments.length){case 0:return f.call(this);case 1:return e.call(this,l);case 2:return d.call(this,l,m);case 3:return c.call(this,l,m,n);default:var q=null;if(3<arguments.length){q=0;for(var u=Array(arguments.length-
3);q<u.length;)u[q]=arguments[q+3],++q;q=new $APP.D(u,0,null)}return k.s(l,m,n,q)}throw Error("Invalid arity: "+arguments.length);};h.I=3;h.K=k.K;h.D=f;h.g=e;h.h=d;h.i=c;h.s=k.s;return h}()};
Qh.i=function(a,b,c){return function(){function d(m,n,p){m=c.i?c.i(m,n,p):c.call(null,m,n,p);m=b.g?b.g(m):b.call(null,m);return a.g?a.g(m):a.call(null,m)}function e(m,n){m=c.h?c.h(m,n):c.call(null,m,n);m=b.g?b.g(m):b.call(null,m);return a.g?a.g(m):a.call(null,m)}function f(m){m=c.g?c.g(m):c.call(null,m);m=b.g?b.g(m):b.call(null,m);return a.g?a.g(m):a.call(null,m)}function h(){var m=c.D?c.D():c.call(null);m=b.g?b.g(m):b.call(null,m);return a.g?a.g(m):a.call(null,m)}var k=null,l=function(){function m(p,
q,u,x){var A=null;if(3<arguments.length){A=0;for(var E=Array(arguments.length-3);A<E.length;)E[A]=arguments[A+3],++A;A=new $APP.D(E,0,null)}return n.call(this,p,q,u,A)}function n(p,q,u,x){p=$APP.id(c,p,q,u,x);p=b.g?b.g(p):b.call(null,p);return a.g?a.g(p):a.call(null,p)}m.I=3;m.K=function(p){var q=$APP.G(p);p=$APP.J(p);var u=$APP.G(p);p=$APP.J(p);var x=$APP.G(p);p=$APP.I(p);return n(q,u,x,p)};m.s=n;return m}();k=function(m,n,p,q){switch(arguments.length){case 0:return h.call(this);case 1:return f.call(this,
m);case 2:return e.call(this,m,n);case 3:return d.call(this,m,n,p);default:var u=null;if(3<arguments.length){u=0;for(var x=Array(arguments.length-3);u<x.length;)x[u]=arguments[u+3],++u;u=new $APP.D(x,0,null)}return l.s(m,n,p,u)}throw Error("Invalid arity: "+arguments.length);};k.I=3;k.K=l.K;k.D=h;k.g=f;k.h=e;k.i=d;k.s=l.s;return k}()};
Qh.s=function(a,b,c,d){var e=lg($APP.V(a,$APP.V(b,$APP.V(c,d))));return function(){function f(k){var l=null;if(0<arguments.length){l=0;for(var m=Array(arguments.length-0);l<m.length;)m[l]=arguments[l+0],++l;l=new $APP.D(m,0,null)}return h.call(this,l)}function h(k){k=$APP.gd($APP.G(e),k);for(var l=$APP.J(e);;)if(l){var m=$APP.G(l);k=m.g?m.g(k):m.call(null,k);l=$APP.J(l)}else return k}f.I=0;f.K=function(k){k=$APP.F(k);return h(k)};f.s=h;return f}()};
Qh.K=function(a){var b=$APP.G(a),c=$APP.J(a);a=$APP.G(c);var d=$APP.J(c);c=$APP.G(d);d=$APP.J(d);return this.s(b,a,c,d)};Qh.I=3;
var pg=function pg(a){switch(arguments.length){case 2:return pg.h(arguments[0],arguments[1]);case 3:return pg.i(arguments[0],arguments[1],arguments[2]);case 4:return pg.G(arguments[0],arguments[1],arguments[2],arguments[3]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return pg.s(arguments[0],arguments[1],arguments[2],arguments[3],new $APP.D(c.slice(4),0,null))}};
pg.h=function(a,b){if(a instanceof $APP.rd){var c=a.state;b=b.g?b.g(c):b.call(null,c);a=ng(a,b)}else a=$APP.zf(a,b);return a};pg.i=function(a,b,c){if(a instanceof $APP.rd){var d=a.state;b=b.h?b.h(d,c):b.call(null,d,c);a=ng(a,b)}else a=$APP.zf(a,b,c);return a};pg.G=function(a,b,c,d){if(a instanceof $APP.rd){var e=a.state;b=b.i?b.i(e,c,d):b.call(null,e,c,d);a=ng(a,b)}else a=$APP.zf(a,b,c,d);return a};
pg.s=function(a,b,c,d,e){return a instanceof $APP.rd?ng(a,$APP.id(b,a.state,c,d,e)):$APP.zf(a,b,c,d,e)};pg.K=function(a){var b=$APP.G(a),c=$APP.J(a);a=$APP.G(c);var d=$APP.J(c);c=$APP.G(d);var e=$APP.J(d);d=$APP.G(e);e=$APP.J(e);return this.s(b,a,c,d,e)};pg.I=4;var og=null;rg.prototype.ib=function(){$APP.v(this.f)&&(this.value=this.f.D?this.f.D():this.f.call(null),this.f=null);return this.value};
rg.prototype.N=function(a,b,c){$APP.pb(b,"#object[cljs.core.Delay ");$APP.cf(new $APP.t(null,2,[$APP.Lf,null==this.f?$APP.Pf:$APP.Nf,$APP.Jf,this.value],null),b,c);return $APP.pb(b,"]")};
var Rh=new $APP.Ob("relax.scene.pendulum","on-resize","relax.scene.pendulum/on-resize",1903299992,null),ah=new $APP.W(null,"y2","y2",-718691301),Zg=new $APP.W(null,"y1","y1",589123466),Sh=new $APP.W(null,"translate","translate",1336199447),Th=new $APP.W(null,"line","line",212345235),Pg=new $APP.W(null,"transform","transform",1381301764),Uh=new $APP.W(null,"y","y",-1757859776),Vh=new $APP.W(null,"x","x",2099068185),Wg=new $APP.W(null,"r","r",-471384190),Jh=new $APP.W(null,"code","code",1586293142),
Wh=new $APP.W(null,"frame","frame",-1711082588),Xh=new $APP.W(null,"on-tick","on-tick",-56973396),lh=new $APP.W(null,"d","d",1972142424),Yg=new $APP.W(null,"x1","x1",-1863922247),$g=new $APP.W(null,"x2","x2",-1362513475),Yh=new $APP.W(null,"click","click",1912301393),xh=new $APP.W(null,"name","name",1843675177),Zh=new $APP.W(null,"lines","lines",-700165781),$h=new $APP.W(null,"rotate","rotate",152705015),Vg=new $APP.W(null,"cy","cy",755331060),zh=new $APP.W(null,"on-resize","on-resize",-2005528129),
Ug=new $APP.W(null,"cx","cx",1272694324),ih=new $APP.W(null,"speed","speed",1257663751),ch=new $APP.W(null,"points","points",-1486596883),Gg=new $APP.W(null,"display","display",242065432),ai=new $APP.W(null,"scene","scene",1523800415),bi=new $APP.W(null,"tris","tris",-1299590805),ci=new $APP.W(null,"viewBox","viewBox",-469489477),di=new $APP.W(null,"keydown","keydown",-629268186),ei=new $APP.W(null,"stroke-width","stroke-width",716836435),fi=new $APP.W(null,"wind-dx","wind-dx",876995195),gi=new $APP.W(null,
"wind-dy","wind-dy",427020537),Hg=new $APP.W(null,"is-fullscreen?","is-fullscreen?",972486782),gh=new $APP.W(null,"fill","fill",883462889),yh=new $APP.W(null,"elem","elem",618631056),hi=new $APP.W(null,"scale","scale",-230427353),uh=new $APP.W(null,"create-scene","create-scene",1581407535),Jg=new $APP.W(null,"can-fullscreen?","can-fullscreen?",-1592427507),ii=new $APP.W(null,"orbits","orbits",820507030),kh=new $APP.W(null,"stroke","stroke",1741823555),ji=new $APP.Ob("relax.scene.wind","on-resize",
"relax.scene.wind/on-resize",1288390222,null),Dh=new $APP.W(null,"scene-id","scene-id",2130439689),ki=new $APP.W(null,"phase","phase",575722892),li=new $APP.W(null,"balls","balls",1987549674),mi=new $APP.Ob("relax.scene.tri","on-resize","relax.scene.tri/on-resize",687052969,null),ni=new $APP.W(null,"wind-x","wind-x",1308864106),Ch=new $APP.W(null,"resize","resize",297367086),oi=new $APP.W(null,"wind-y","wind-y",1527264039);var Mg=new $APP.X(null,4,5,$APP.Y,[Sh,$h,hi,new $APP.W(null,"skew","skew",-595121815)],null),pi=function(a){if($APP.nc(a))return $APP.lc(a,null);a=$APP.F(a);if(null==a)return $APP.If;if(a instanceof $APP.D&&0===a.o){a=a.j;for(var b=a.length,c=$APP.sb($APP.If),d=0;;)if(d<b)$APP.tb(c,a[d]),d+=1;else break;return $APP.ub(c)}for(c=$APP.sb($APP.If);;)if(null!=a)b=$APP.J(a),c=$APP.tb(c,$APP.B(a)),a=b;else return $APP.ub(c)}(Mg),qi=$APP.td.h(pi,Pg),ri=function ri(a){for(var c=[],d=arguments.length,e=0;;)if(e<
d)c.push(arguments[e]),e+=1;else break;return ri.s(arguments[0],1<c.length?new $APP.D(c.slice(1),0,null):null)};
ri.s=function(a,b){if($APP.F(b)){a:{var c=$APP.F(b);$APP.G(c);c=$APP.J(c);$APP.G(c);$APP.J(c);c=$APP.vd;for(var d=b;;){b=c;d=$APP.F(d);c=$APP.G(d);d=$APP.J(d);var e=$APP.G(d),f=$APP.J(d);d=e;e=f;if($APP.Da(c))break a;f=qi.g?qi.g(c):qi.call(null,c);$APP.v(f)||a.setAttributeNS(null,$APP.Qe(c),$APP.z.g(d));b=$APP.v(f)?$APP.td.h(b,new $APP.X(null,2,5,$APP.Y,[c,d],null)):b;d=e;c=b}}if($APP.F(b)){b=Qg(a,b);c=$APP.F(pi);d=null;for(f=e=0;;)if(f<e){var h=d.M(null,f),k=h.g?h.g(b):h.call(null,b);a[h]=k;f+=1}else if(c=
$APP.F(c))$APP.uc(c)?(e=$APP.xb(c),c=$APP.yb(c),d=e,e=$APP.M(e)):(d=$APP.G(c),e=d.g?d.g(b):d.call(null,b),a[d]=e,c=$APP.J(c),d=null,e=0),f=0;else break;a.setAttributeNS(null,"transform",Ng(b))}}return a};ri.I=1;ri.K=function(a){var b=$APP.G(a);a=$APP.J(a);return this.s(b,a)};var Tg=function Tg(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return Tg.s(arguments[0],1<c.length?new $APP.D(c.slice(1),0,null):null)};
Tg.s=function(a,b){a=document.createElementNS("http://www.w3.org/2000/svg",a);var c=$APP.rc($APP.G(b))?new $APP.X(null,2,5,$APP.Y,[$APP.G(b),$APP.I(b)],null):new $APP.X(null,2,5,$APP.Y,[null,b],null);b=$APP.N.i(c,0,null);c=$APP.N.i(c,1,null);a.translate=new $APP.X(null,2,5,$APP.Y,[0,0],null);a.rotate=0;a.scale=1;b=$APP.gd($APP.Df,$APP.hd($APP.df,$APP.Kc,$APP.R([b])));$APP.hd(ri,a,b);b=$APP.F(c);c=null;for(var d=0,e=0;;)if(e<d){var f=c.M(null,e);$APP.oc(f)?Rg(a,f):Sg(a,$APP.R([f]));e+=1}else if(b=
$APP.F(b))c=b,$APP.uc(c)?(b=$APP.xb(c),e=$APP.yb(c),c=b,d=$APP.M(b),b=e):(b=$APP.G(c),$APP.oc(b)?Rg(a,b):Sg(a,$APP.R([b])),b=$APP.J(c),c=null,d=0),e=0;else break;return a};Tg.I=1;Tg.K=function(a){var b=$APP.G(a);a=$APP.J(a);return this.s(b,a)};var si=gg(Tg,"svg"),fh=gg(Tg,"g");var eh=$APP.M($APP.Tf),ti=function(){var a=Qh.h(xg(100),wg(new $APP.X(null,2,5,$APP.Y,[0,90],null),new $APP.X(null,2,5,$APP.Y,[100,0],null)));return function(b){return a(90<b&&180>b?b-90:270<b&&360>b?b-270:100)}}(),ui=wg(new $APP.X(null,2,5,$APP.Y,[0,100],null),new $APP.X(null,2,5,$APP.Y,[40,100],null)),vi=wg(new $APP.X(null,2,5,$APP.Y,[0,100],null),new $APP.X(null,2,5,$APP.Y,[20,60],null)),hh=wg(new $APP.X(null,2,5,$APP.Y,[0,eh],null),new $APP.X(null,2,5,$APP.Y,[200,300],null));var wi=Qh.h(xg(1),wg(new $APP.X(null,2,5,$APP.Y,[0,400],null),new $APP.X(null,2,5,$APP.Y,[0,1],null)));var xi=Math.PI,qh=Math.sin,rh=Math.cos,yi=2*xi,ph=yi/3,zi=10*yi/6E5,Ai=(20*yi/6E5-zi)/25,nh=function(){var a=$APP.Kd(function(){return function d(c){return new $APP.Sc(null,function(){for(;;){var e=$APP.F(c);if(e){if($APP.uc(e)){var f=$APP.xb(e),h=$APP.M(f),k=$APP.Vc(h);a:for(var l=0;;)if(l<h){var m=$APP.ic(f,l);k.add(20+19.2*m);l+=1}else{f=!0;break a}return f?$APP.Yc(k.H(),d($APP.yb(e))):$APP.Yc(k.H(),null)}k=$APP.G(e);return $APP.V(20+19.2*k,d($APP.I(e)))}return null}},null)}(fg(25))}());return gg($APP.N,
a)}(),oh=function(){var a=$APP.Kd(function(){return function d(c){return new $APP.Sc(null,function(){for(;;){var e=$APP.F(c);if(e){if($APP.uc(e)){var f=$APP.xb(e),h=$APP.M(f),k=$APP.Vc(h);a:for(var l=0;;)if(l<h){var m=$APP.ic(f,l);k.add(zi+m*Ai);l+=1}else{f=!0;break a}return f?$APP.Yc(k.H(),d($APP.yb(e))):$APP.Yc(k.H(),null)}k=$APP.G(e);return $APP.V(zi+k*Ai,d($APP.I(e)))}return null}},null)}(fg(25))}());return gg($APP.N,a)}();var th=new $APP.X(null,3,5,$APP.Y,[new $APP.t(null,4,[xh,"pendulum",uh,function(){var a=$APP.wd(jh,fg(eh)),b=$APP.wd(mh,fg(eh)),c=Sg(Sg(fh(),$APP.R([fh(new $APP.t(null,2,[ei,1,gh,"none"],null),b)])),$APP.R([fh(new $APP.t(null,1,[ei,2],null),a)]));return new $APP.t(null,4,[yh,si(new $APP.t(null,2,[$APP.Mf,"ar-2-1",ci,"0 0 0 0"],null),c),ai,c,li,a,ii,b],null)},zh,function(a){var b=yh.g(a),c=ai.g(a),d=$APP.pf(b,"clientWidth"),e=$APP.pf(b,"clientHeight");var f=d/2E3;var h=e/1E3;f=f<h?f:h;console.log(Rh,
d,"x",e,"\x3d\x3e",f);ri.s(b,$APP.R([ci,["0 0 ",$APP.z.g(d)," ",$APP.z.g(e)].join("")]));ri.s(c,$APP.R([Sh,new $APP.X(null,2,5,$APP.Y,[.5*d,e],null),hi,f,$h,-90]));return a},Xh,function(a,b){var c=$APP.od(a),d=$APP.S.h(c,li);c=$APP.S.h(c,ii);for(var e=$APP.F(fg(eh)),f=null,h=0,k=0;;)if(k<h){var l=f.M(null,k),m=$APP.N.h(d,l),n=$APP.N.h(c,l),p=(b*$APP.pf(m,ih)%360+360)%360,q=90<p&&270>p?"d":"r",u=ti(p);ri.s(n,$APP.R([kh,["hsl(0 0% ",$APP.z.g(vi(u)),"%)"].join("")]));ri.s(m,$APP.R([Pg,["rotate(",$APP.z.g(90>
p?p:270>p?90-(p-90):-90+(p-270)),")"].join(""),kh,["hsl(0 0% ",$APP.z.g(ui(u)),"%)"].join("")]));n=m.getAttributeNS(null,$APP.Qe(ki));$APP.fc.h(n,q)||(ri.s(m,$APP.R([ki,q])),Dg(l,$APP.fc.h(q,"r")?-.9:.9));k+=1}else if(e=$APP.F(e))$APP.uc(e)?(h=$APP.xb(e),e=$APP.yb(e),f=h,h=$APP.M(h)):(f=$APP.G(e),h=$APP.N.h(d,f),l=$APP.N.h(c,f),m=(b*$APP.pf(h,ih)%360+360)%360,k=90<m&&270>m?"d":"r",q=ti(m),ri.s(l,$APP.R([kh,["hsl(0 0% ",$APP.z.g(vi(q)),"%)"].join("")])),ri.s(h,$APP.R([Pg,["rotate(",$APP.z.g(90>m?m:
270>m?90-(m-90):-90+(m-270)),")"].join(""),kh,["hsl(0 0% ",$APP.z.g(ui(q)),"%)"].join("")])),l=h.getAttributeNS(null,$APP.Qe(ki)),$APP.fc.h(l,k)||(ri.s(h,$APP.R([ki,k])),Dg(f,$APP.fc.h(k,"r")?-.9:.9)),e=$APP.J(e),f=null,h=0),k=0;else break;return a}],null),new $APP.t(null,4,[xh,"wind",uh,function(){var a=function(){return function e(d){return new $APP.Sc(null,function(){for(var f=d;;){var h=$APP.F(f);if(h){var k=h,l=$APP.G(k);if(h=$APP.F(function(m,n,p,q){return function A(x){return new $APP.Sc(null,
function(E,K){return function(){for(;;){var Q=$APP.F(x);if(Q){if($APP.uc(Q)){var T=$APP.xb(Q),ca=$APP.M(T),U=$APP.Vc(ca);a:for(var Ea=0;;)if(Ea<ca){var pa=$APP.ic(T,Ea),Ga=fh(new $APP.t(null,1,[Pg,["translate(",$APP.z.g(K)," ",$APP.z.g(pa),")"].join("")],null)),xa=fh(new $APP.t(null,1,[Pg,"scale(0) rotate(0)"],null),bh(0,0,0,30));pa=new $APP.t(null,4,[Vh,K,Uh,pa,Wh,Sg(Ga,$APP.R([xa])),Th,xa],null);U.add(pa);Ea+=1}else{T=!0;break a}return T?$APP.Yc(U.H(),A($APP.yb(Q))):$APP.Yc(U.H(),null)}U=$APP.G(Q);
T=fh(new $APP.t(null,1,[Pg,["translate(",$APP.z.g(K)," ",$APP.z.g(U),")"].join("")],null));ca=fh(new $APP.t(null,1,[Pg,"scale(0) rotate(0)"],null),bh(0,0,0,30));return $APP.V(new $APP.t(null,4,[Vh,K,Uh,U,Wh,Sg(T,$APP.R([ca])),Th,ca],null),A($APP.I(Q)))}return null}}}(m,n,p,q),null)}}(f,l,k,h)(eg(50,1E3,50))))return $APP.Df.h(h,e($APP.I(f)));f=$APP.I(f)}else return null}},null)}(eg(50,2E3,50))}(),b=fh(new $APP.t(null,2,[ei,1,kh,"white"],null),$APP.df.h(Wh,a));return new $APP.t(null,7,[yh,si(new $APP.t(null,
2,[$APP.Mf,"ar-2-1",ci,"0 0 0 0"],null),b),ai,b,ni,1E3,fi,.9,oi,500,gi,.45,Zh,a],null)},zh,function(a){var b=yh.g(a),c=ai.g(a),d=$APP.pf(b,"clientWidth"),e=$APP.pf(b,"clientHeight");var f=d/2E3;var h=e/1E3;f=f<h?f:h;console.log(ji,d,"x",e,"\x3d\x3e",f);ri.s(b,$APP.R([ci,["0 0 ",$APP.z.g(d)," ",$APP.z.g(e)].join("")]));ri.s(c,$APP.R([Pg,["scale(",$APP.z.g(f),")"].join("")]));return a},Xh,function(a){for(var b=fi.g(a),c=ni.g(a)+b,d=gi.g(a),e=oi.g(a)+d,f=$APP.F(Zh.g(a)),h=null,k=0,l=0;;)if(l<k){var m=
h.M(null,l);m=$APP.od(m);var n=$APP.S.h(m,Vh),p=$APP.S.h(m,Uh);m=$APP.S.h(m,Th);n=c-n;var q=e-p;p=wi(Math.sqrt(n*n+q*q));n=180*Math.atan2(q,n)/Math.PI-90;ri.s(m,$APP.R([Pg,["scale(",$APP.z.g(p),") rotate(",$APP.z.g(n),")"].join("")]));l+=1}else if(f=$APP.F(f))$APP.uc(f)?(k=$APP.xb(f),f=$APP.yb(f),h=k,k=$APP.M(k)):(h=$APP.G(f),h=$APP.od(h),l=$APP.S.h(h,Vh),k=$APP.S.h(h,Uh),h=$APP.S.h(h,Th),l=c-l,m=e-k,k=wi(Math.sqrt(l*l+m*m)),l=180*Math.atan2(m,l)/Math.PI-90,ri.s(h,$APP.R([Pg,["scale(",$APP.z.g(k),
") rotate(",$APP.z.g(l),")"].join("")])),f=$APP.J(f),h=null,k=0),l=0;else break;return $APP.Z.i($APP.Z.i($APP.Z.i($APP.Z.i(a,ni,c),oi,e),fi,0>c||2E3<c?-b:b),gi,0>e||1E3<e?-d:d)}],null),new $APP.t(null,4,[xh,"tris",uh,function(){var a=$APP.Kd(function(){return function h(f){return new $APP.Sc(null,function(){for(var k=f;;){var l=$APP.F(k);if(l){var m=l,n=$APP.G(m);if(l=$APP.F(function(p,q,u,x){return function K(E){return new $APP.Sc(null,function(Q,T){return function(){for(;;){var ca=$APP.F(E);if(ca){if($APP.uc(ca)){var U=
$APP.xb(ca),Ea=$APP.M(U),pa=$APP.Vc(Ea);a:for(var Ga=0;;)if(Ga<Ea){var xa=$APP.ic(U,Ga),Ha=sh(T,xa,0);xa=$APP.N.i(Ha,0,null);Ha=$APP.N.i(Ha,1,null);xa=Xg(new $APP.t(null,3,[ei,2,kh,"hsl(257 35% 39%)",gh,"hsl(0 0% 10%)"],null),xa,Ha,7);pa.add(xa);Ga+=1}else{U=!0;break a}return U?$APP.Yc(pa.H(),K($APP.yb(ca))):$APP.Yc(pa.H(),null)}pa=$APP.G(ca);U=sh(T,pa,0);pa=$APP.N.i(U,0,null);U=$APP.N.i(U,1,null);return $APP.V(Xg(new $APP.t(null,3,[ei,2,kh,"hsl(257 35% 39%)",gh,"hsl(0 0% 10%)"],null),pa,U,7),K($APP.I(ca)))}return null}}}(p,
q,u,x),null)}}(k,n,m,l)(fg(3))))return $APP.Df.h(l,h($APP.I(k)));k=$APP.I(k)}else return null}},null)}(fg(25))}()),b=$APP.Kd(function(){return function h(f){return new $APP.Sc(null,function(){for(;;){var k=$APP.F(f);if(k){var l=k;if($APP.uc(l)){var m=$APP.xb(l),n=$APP.M(m),p=$APP.Vc(n);return function(){for(var u=0;;)if(u<n){var x=$APP.ic(m,u);$APP.Zc(p,fh(new $APP.t(null,1,[Pg,"rotate(0)"],null),dh(new $APP.t(null,3,[ei,1,kh,"hsl(257 35% 23%)",gh,"none"],null),$APP.df.h(function(A,E){return function(K){return sh(E,
K,0)}}(u,x,m,n,p,l,k,a),fg(4))),kg(3,jg(3*x,a))));u+=1}else return!0}()?$APP.Yc(p.H(),h($APP.yb(l))):$APP.Yc(p.H(),null)}var q=$APP.G(l);return $APP.V(fh(new $APP.t(null,1,[Pg,"rotate(0)"],null),dh(new $APP.t(null,3,[ei,1,kh,"hsl(257 35% 23%)",gh,"none"],null),$APP.df.h(function(u){return function(x){return sh(u,x,0)}}(q,l,k,a),fg(4))),kg(3,jg(3*q,a))),h($APP.I(l)))}return null}},null)}(fg(25))}()),c=$APP.Kd(function(){return function h(f){return new $APP.Sc(null,function(){for(var k=f;;){var l=$APP.F(k);
if(l){var m=l,n=$APP.G(m);if(l=$APP.F(function(p,q,u,x,A,E){return function T(Q){return new $APP.Sc(null,function(ca,U){return function(){for(;;){var Ea=$APP.F(Q);if(Ea){if($APP.uc(Ea)){var pa=$APP.xb(Ea),Ga=$APP.M(pa),xa=$APP.Vc(Ga);a:for(var Ha=0;;)if(Ha<Ga){var pc=$APP.ic(pa,Ha),ob=sh(U,pc,0),qc=$APP.N.i(ob,0,null);ob=$APP.N.i(ob,1,null);var Hb=sh(U+1,pc,0);pc=$APP.N.i(Hb,0,null);Hb=$APP.N.i(Hb,1,null);qc=bh(qc,ob,pc,Hb);xa.add(qc);Ha+=1}else{pa=!0;break a}return pa?$APP.Yc(xa.H(),T($APP.yb(Ea))):
$APP.Yc(xa.H(),null)}Ga=$APP.G(Ea);pa=sh(U,Ga,0);xa=$APP.N.i(pa,0,null);pa=$APP.N.i(pa,1,null);Ha=sh(U+1,Ga,0);Ga=$APP.N.i(Ha,0,null);Ha=$APP.N.i(Ha,1,null);return $APP.V(bh(xa,pa,Ga,Ha),T($APP.I(Ea)))}return null}}}(p,q,u,x,A,E),null)}}(k,n,m,l,a,b)(fg(3))))return $APP.Df.h(l,h($APP.I(k)));k=$APP.I(k)}else return null}},null)}(fg(24))}()),d=fh(fh(new $APP.t(null,3,[ei,1,kh,"hsl(257 35% 39%)",gh,"none"],null),c),fh(b));return new $APP.t(null,5,[yh,si(new $APP.t(null,2,[$APP.Mf,"ar-1-1",ci,"0 0 0 0"],
null),d),ai,d,bi,b,li,a,Zh,c],null)},zh,function(a){var b=yh.g(a),c=ai.g(a),d=$APP.pf(b,"clientWidth"),e=$APP.pf(b,"clientHeight");var f=d/1E3;var h=e/1E3;f=f<h?f:h;console.log(mi,d,"x",e,"\x3d\x3e",f);ri.s(b,$APP.R([ci,["0 0 ",$APP.z.g(d)," ",$APP.z.g(e)].join("")]));ri.s(c,$APP.R([Pg,["translate(",$APP.z.g(.5*d)," ",$APP.z.g(.5*e),") scale(",$APP.z.g(f),") rotate(-90)"].join("")]));return a},Xh,function(a,b){var c=$APP.od(a),d=$APP.S.h(c,bi),e=$APP.S.h(c,Zh);cg($APP.df.i(function(f,h){return ri.s(f,
$APP.R([Pg,["rotate(-",$APP.z.g(h),")"].join("")]))},d,function(){return function k(h){return new $APP.Sc(null,function(){for(;;){var l=$APP.F(h);if(l){if($APP.uc(l)){var m=$APP.xb(l),n=$APP.M(m),p=$APP.Vc(n);a:for(var q=0;;)if(q<n){var u=$APP.ic(m,q),x=p,A=b;u=oh(u);x.add(A*u/xi*180);q+=1}else{m=!0;break a}return m?$APP.Yc(p.H(),k($APP.yb(l))):$APP.Yc(p.H(),null)}m=$APP.G(l);p=b;m=oh(m);return $APP.V(p*m/xi*180,k($APP.I(l)))}return null}},null)}(fg(25))}()));cg($APP.df.i(function(f,h){var k=$APP.N.i(h,
0,null),l=$APP.N.i(k,0,null);k=$APP.N.i(k,1,null);var m=$APP.N.i(h,1,null);h=$APP.N.i(m,0,null);m=$APP.N.i(m,1,null);return ri.s(f,$APP.R([Yg,l,Zg,k,$g,h,ah,m]))},e,function(){return function k(h){return new $APP.Sc(null,function(){for(var l=h;;){var m=$APP.F(l);if(m){var n=m,p=$APP.G(n);if(m=$APP.F(function(q,u,x,A,E,K,Q,T){return function Ea(U){return new $APP.Sc(null,function(pa,Ga){return function(){for(;;){var xa=$APP.F(U);if(xa){if($APP.uc(xa)){var Ha=$APP.xb(xa),pc=$APP.M(Ha),ob=$APP.Vc(pc);
a:for(var qc=0;;)if(qc<pc){var Hb=$APP.ic(Ha,qc);Hb=new $APP.X(null,2,5,$APP.Y,[sh(Ga,Hb,b),sh(Ga+1,Hb,b)],null);ob.add(Hb);qc+=1}else{Ha=!0;break a}return Ha?$APP.Yc(ob.H(),Ea($APP.yb(xa))):$APP.Yc(ob.H(),null)}ob=$APP.G(xa);return $APP.V(new $APP.X(null,2,5,$APP.Y,[sh(Ga,ob,b),sh(Ga+1,ob,b)],null),Ea($APP.I(xa)))}return null}}}(q,u,x,A,E,K,Q,T),null)}}(l,p,n,m,a,c,d,e)(fg(3))))return $APP.Df.h(m,k($APP.I(l)));l=$APP.I(l)}else return null}},null)}(fg(24))}()));return a}],null)],null),vh=new $APP.rd(null),
wh=new $APP.rd(null);var Lh=Ih(-1),Kh=Ih(1);var Nh=new rg(function(){mg($APP.R(["init: registering worker..."]));$APP.pf(navigator,"serviceWorker").register("worker.js",{scope:"./"}).then(function(){return mg($APP.R(["init: worker registered"]))}).catch(function(b){return mg($APP.R(["init: worker failed",b]))});mg($APP.R(["init: init modules"]));ug($APP.Kf,Eg);pg.G($APP.Qf,$APP.Z,$APP.Kf,!1);Kg();Cg("fullscreen",Yh,Hh);Cg("sound",Yh,Gh);Cg("prev",Yh,Lh);Cg("next",Yh,Kh);Cg(window,di,Mh);Eh();mg($APP.R(["init: animation"]));var a=$APP.pf(window,
"performance").now();return window.requestAnimationFrame(function d(c){c-=a;var e=$APP.ab(vh);e=$APP.N.h(th,e);pg.i(wh,Xh.g(e),c);return window.requestAnimationFrame(d)})}),Bi=["relax","app","run"],Ci=$APP.tf;Bi[0]in Ci||"undefined"==typeof Ci.execScript||Ci.execScript("var "+Bi[0]);for(var Di;Bi.length&&(Di=Bi.shift());)Bi.length||void 0===Oh?Ci=Ci[Di]&&Ci[Di]!==Object.prototype[Di]?Ci[Di]:Ci[Di]={}:Ci[Di]=Oh;
}).call(this);