(function(){
shadow$provide[0]=function(b,c,a,d){a.exports=Howl};
'use strict';var cf=function(a,b){return $APP.aa[a]=b},df=function(){},ef=function(a){if(null!=a&&null!=a.Ta)a=a.Ta(a);else{var b=ef[$APP.t(null==a?null:a)];if(null!=b)a=b.g?b.g(a):b.call(null,a);else if(b=ef._,null!=b)a=b.g?b.g(a):b.call(null,a);else throw $APP.x("IReversible.-rseq",a);}return a},ff=function(a,b){if(null!=a&&null!=a.Pb)a=a.Pb(a,b);else{var c=ff[$APP.t(null==a?null:a)];if(null!=c)a=c.h?c.h(a,b):c.call(null,a,b);else if(c=ff._,null!=c)a=c.h?c.h(a,b):c.call(null,a,b);else throw $APP.x("IReset.-reset!",
a);}return a},gf=function(a){if(null==$APP.qa)throw Error("No *print-fn* fn set for evaluation environment");$APP.qa.call(null,a)},jf=function(){var a=hf;return 0>=a?$APP.I:$APP.ec(0)&&$APP.ec(a)&&$APP.ec(1)?new $APP.qe(null,0,a,1,null,null,null):new $APP.re(null,0,a,1,null,null,null)},lf=function(a){var b=kf;return function(){function c(l,m,n){return b.H?b.H(a,l,m,n):b.call(null,a,l,m,n)}function d(l,m){return b.j?b.j(a,l,m):b.call(null,a,l,m)}function e(l){return b.h?b.h(a,l):b.call(null,a,l)}function f(){return b.g?
b.g(a):b.call(null,a)}var h=null,k=function(){function l(n,p,q,r){var w=null;if(3<arguments.length){w=0;for(var y=Array(arguments.length-3);w<y.length;)y[w]=arguments[w+3],++w;w=new $APP.F(y,0,null)}return m.call(this,n,p,q,w)}function m(n,p,q,r){return $APP.Pc(b,a,n,p,q,$APP.Q([r]))}l.I=3;l.G=function(n){var p=$APP.H(n);n=$APP.K(n);var q=$APP.H(n);n=$APP.K(n);var r=$APP.H(n);n=$APP.Bb(n);return m(p,q,r,n)};l.v=m;return l}();h=function(l,m,n,p){switch(arguments.length){case 0:return f.call(this);
case 1:return e.call(this,l);case 2:return d.call(this,l,m);case 3:return c.call(this,l,m,n);default:var q=null;if(3<arguments.length){q=0;for(var r=Array(arguments.length-3);q<r.length;)r[q]=arguments[q+3],++q;q=new $APP.F(r,0,null)}return k.v(l,m,n,q)}throw Error("Invalid arity: "+arguments.length);};h.I=3;h.G=k.G;h.C=f;h.g=e;h.h=d;h.j=c;h.v=k.v;return h}()},mf=function(a){return(null!=a?a.l&134217728||$APP.E===a.lc||(a.l?0:$APP.v(df,a)):$APP.v(df,a))?(a=ef(a))?a:$APP.I:$APP.kc($APP.Xc,$APP.I,a)},
nf=function(a){var b=$APP.Fe.j($APP.oa(),$APP.ka,!1);gf($APP.He(a,b));$APP.u($APP.pa)?(a=$APP.oa(),gf("\n"),a=($APP.U.h(a,$APP.ja),null)):a=null;return a},of=function(a){this.state=a;this.Cb=this.$b=this.u=null;this.B=16386;this.l=6455296},pf=function(a,b){if(a instanceof of){var c=a.$b;if(null!=c&&!$APP.u(c.g?c.g(b):c.call(null,b)))throw Error("Validator rejected reference state");c=a.state;a.state=b;if(null!=a.Cb)a:for(var d=$APP.G(a.Cb),e=null,f=0,h=0;;)if(h<f){var k=e.K(null,h),l=$APP.T(k,0,null);
k=$APP.T(k,1,null);k.H?k.H(l,a,c,b):k.call(null,l,a,c,b);h+=1}else if(d=$APP.G(d))$APP.bc(d)?(e=$APP.hb(d),d=$APP.ib(d),l=e,f=$APP.M(e),e=l):(e=$APP.H(d),l=$APP.T(e,0,null),k=$APP.T(e,1,null),k.H?k.H(l,a,c,b):k.call(null,l,a,c,b),d=$APP.K(d),e=null,f=0),h=0;else break a;return b}return ff(a,b)},qf=function(a,b){var c=$APP.G(b);$APP.H(c);c=$APP.K(c);$APP.H(c);for($APP.K(c);;){c=$APP.G(b);b=$APP.H(c);c=$APP.K(c);var d=$APP.H(c),e=$APP.K(c);c=d;d=e;e=a;e.setAttributeNS.call(e,null,$APP.ne(b),$APP.z.g(c));
if(d)b=d;else return a}},rf=function(a,b){return a.getAttributeNS.call(a,null,$APP.ne(b))},vf=function(a,b){var c=sf[a];if(void 0!==c)return c;try{tf.push(a);var d=uf[a],e=shadow$provide[a];if(void 0===d){if(void 0===e)throw"Module not provided: "+a;d={exports:{}};uf[a]=d}if(e){delete shadow$provide[a];try{e.call(d,$APP.Ne,vf,d,d.exports)}catch(h){throw console.warn("shadow-cljs - failed to load",a),h;}if(b){var f=b.globals;if(f)for(a=0;a<f.length;a++)window[f[a]]=d.exports}}}finally{tf.pop()}return d.exports},
wf=function(a,b){var c=$APP.T(a,0,null);a=$APP.T(a,1,null);var d=$APP.T(b,0,null);b=$APP.T(b,1,null);var e=a-c,f=b-d;return function(h){return d+(h-c)/e*f}},xf=function(){return function(a){return 0>a?0:100<a?100:a}},yf=function(a){if("string"===typeof a){var b=document;return b.getElementById.call(b,a)}return a},zf=function(a,b){a=yf(a);var c=$APP.G(b);$APP.H(c);c=$APP.K(c);$APP.H(c);for($APP.K(c);;){c=$APP.G(b);b=$APP.H(c);c=$APP.K(c);var d=$APP.H(c),e=$APP.K(c);c=d;d=e;e=a;e.setAttribute.call(e,
$APP.ne(b),$APP.z.g(c));if($APP.G(d))b=d;else return a}},Af=function(a,b){a=yf(a);(null!=a?a:{}).textContent=b;return a},Bf=function(a){a=$APP.Zb($APP.H(a))?new $APP.X(null,2,5,$APP.Ae,[$APP.H(a),$APP.Bb(a)],null):new $APP.X(null,2,5,$APP.Ae,[null,a],null);var b=$APP.T(a,0,null),c=$APP.T(a,1,null);a=document;a=a.createElement.call(a,"div");b=$APP.G(b);for(var d=null,e=0,f=0;;)if(f<e){var h=d.K(null,f),k=$APP.T(h,0,null);h=$APP.T(h,1,null);var l=a;l.setAttribute.call(l,$APP.ne(k),$APP.z.g(h));f+=1}else if(b=
$APP.G(b))$APP.bc(b)?(e=$APP.hb(b),b=$APP.ib(b),d=e,e=$APP.M(e)):(e=$APP.H(b),d=$APP.T(e,0,null),e=$APP.T(e,1,null),f=a,f.setAttribute.call(f,$APP.ne(d),$APP.z.g(e)),b=$APP.K(b),d=null,e=0),f=0;else break;c=$APP.G(c);b=null;for(e=d=0;;)if(e<d)f=b.K(null,e),k=a,k.append.call(k,f),e+=1;else if(c=$APP.G(c))$APP.bc(c)?(d=$APP.hb(c),c=$APP.ib(c),b=d,d=$APP.M(d)):(b=$APP.H(c),d=a,d.append.call(d,b),c=$APP.K(c),b=null,d=0),e=0;else break;return a},Cf=function(a){var b=yf("app");a=$APP.G(a);for(var c=null,
d=0,e=0;;)if(e<d){var f=c.K(null,e),h=b;h.append.call(h,f);e+=1}else if(a=$APP.G(a))$APP.bc(a)?(d=$APP.hb(a),a=$APP.ib(a),c=d,d=$APP.M(d)):(c=$APP.H(a),d=b,d.append.call(d,c),a=$APP.K(a),c=null,d=0),e=0;else break},Ef=function(a){Af(zf(yf("fullscreen"),$APP.Q([Df,$APP.u(a)?"on":"off"])),$APP.u(a)?"Fullscreen: ON":"Fullscreen: OFF");if($APP.u(a)){a=yf("wrapper");var b=a.requestFullscreen;return b.call(a)}a=document;a=a.exitFullscreen.call(a);b=a.then;return b.call(a,$APP.qc,$APP.qc)},Ff=function(a){return Af(zf(yf("audio"),
$APP.Q([Df,$APP.u(a)?"on":"off"])),$APP.u(a)?"Audio: ON":"Audio: OFF")},Kf=function(a){var b=yf("app");b=null!=b?b.clientWidth:void 0;a=null!=a?a.clientX:void 0;a<.5*b?$APP.u($APP.C(Gf))?(a=Hf.h(If,$APP.ua),a=Ef(a)):a=null:(a=Hf.h(Jf,$APP.ua),a=Ff(a));return a},Nf=function(){var a=document;a=null!=a?a.exitFullscreen:void 0;null!=a&&(pf(Gf,!0),Cf($APP.Q([Bf($APP.Q([new $APP.ia(null,2,[Lf,"fullscreen",Mf,"toggle"],null)]))])),Ef($APP.C(If)));Cf($APP.Q([Bf($APP.Q([new $APP.ia(null,2,[Lf,"audio",Mf,"toggle"],
null)]))]));Ff($APP.C(Jf))},Tf=function(a){var b=$APP.Uc(a);a=$APP.U.h(b,Of);b=$APP.U.h(b,Pf);var c=null!=a?a.clientWidth:void 0;var d=null!=a?a.clientHeight:void 0;var e=c/2E3;var f=d/1E3;e=e<f?e:f;console.log(Qf,c,"x",d,"\x3d\x3e",e);qf(a,$APP.Q([Rf,["0 0 ",$APP.z.g(c)," ",$APP.z.g(d)].join("")]));return qf(b,$APP.Q([Sf,["translate(",$APP.z.g(.5*c)," ",$APP.z.g(d),") scale(",$APP.z.g(e),")rotate(-90)"].join("")]))},bg=function(a){return Uf(new $APP.ia(null,1,[Vf,180*(20+.5*a)/3E5],null),Wf(new $APP.ia(null,
4,[Xf,100+1E3/(hf+2)*a,Yf,0,Zf,15,$f,["hsl(",$APP.z.g(ag(a))," 100% 50%)"].join("")],null)))},fg=function(a){a=100+1E3/(hf+2)*a;return cg(new $APP.ia(null,2,[dg,"hsl(0 0% 30%)",eg,["M 0,",$APP.z.g(-a)," A ",$APP.z.g(a)," ",$APP.z.g(a)," 180 1 1 0,",$APP.z.g(a)].join("")],null))},ng=function(){var a=gg,b=$APP.$c(bg,jf()),c=$APP.$c(fg,jf()),d=hg.v(hg.v(Uf(),$APP.Q([Uf(new $APP.ia(null,2,[ig,1,$f,"none"],null),c)])),$APP.Q([Uf(new $APP.ia(null,1,[ig,2],null),b)]));return new $APP.ia(null,5,[Of,jg(new $APP.ia(null,
1,[Rf,"0 0 0 0"],null),d),kg,a,Pf,d,lg,b,mg,c],null)},tg=function(a,b){return function e(d){if($APP.u($APP.C(a))){a:{var f=$APP.Uc(b),h=$APP.U.h(f,kg),k=$APP.U.h(f,lg);f=$APP.U.h(f,mg);d-=h;h=$APP.C(Jf);for(var l=$APP.G(jf()),m=null,n=0,p=0;;)if(p<n){var q=m.K(null,p),r=$APP.Qb(k,q),w=$APP.Qb(f,q),y=parseFloat(rf(r,Vf)),B=(d*y%360+360)%360;y=90<B&&270>B?"d":"r";var J=og(B);qf(w,$APP.Q([dg,["hsl(0 0% ",$APP.z.g(pg(J)),"%)"].join("")]));qf(r,$APP.Q([Sf,["rotate(",$APP.z.g(90>B?B:270>B?90-(B-90):-90+
(B-270)),")"].join(""),dg,["hsl(0 0% ",$APP.z.g(qg(J)),"%)"].join("")]));w=rf(r,rg);$APP.N.h(w,y)||(qf(r,$APP.Q([rg,y])),$APP.u(h)&&(r=q=$APP.Qb(sg,q),r.stereo.call(r,$APP.N.h(y,"r")?-.9:.9),q.play.call(q)));p+=1}else if(q=$APP.G(l))l=q,$APP.bc(l)?(m=$APP.hb(l),l=$APP.ib(l),q=m,n=$APP.M(m),m=q):(q=$APP.H(l),n=$APP.Qb(k,q),p=$APP.Qb(f,q),m=parseFloat(rf(n,Vf)),y=(d*m%360+360)%360,m=90<y&&270>y?"d":"r",r=og(y),qf(p,$APP.Q([dg,["hsl(0 0% ",$APP.z.g(pg(r)),"%)"].join("")])),qf(n,$APP.Q([Sf,["rotate(",
$APP.z.g(90>y?y:270>y?90-(y-90):-90+(y-270)),")"].join(""),dg,["hsl(0 0% ",$APP.z.g(qg(r)),"%)"].join("")])),p=rf(n,rg),$APP.N.h(p,m)||(qf(n,$APP.Q([rg,m])),$APP.u(h)&&(n=q=$APP.Qb(sg,q),n.stereo.call(n,$APP.N.h(m,"r")?-.9:.9),q.play.call(q))),l=$APP.K(l),m=null,n=0),p=0;else break a}k=window;return k.requestAnimationFrame.call(k,e)}return null}},wg=function(){var a=new AbortController;var b=null!=a?a.signal:void 0;var c={signal:b};b=new of(!0);var d=ng();pf(ug,a);pf(vg,b);a=window;a.addEventListener.call(a,
"resize",function(){return Tf(d)},c);a=document;a.addEventListener.call(a,"click",Kf,c);c=yf("app");c.appendChild.call(c,Of.g(d));Nf();Tf(d);c=window;return c.requestAnimationFrame.call(c,tg(b,d))},xg=function(){nf($APP.Q(["init-worker: registering..."]));var a=function(){var b=function(){var c=navigator.serviceWorker;return c.register.call(c,"worker.js",{scope:"./"})}();return b.then.call(b,function(){return nf($APP.Q(["init-worker: registered"]))})}();a["catch"].call(a,function(b){return nf($APP.Q(["init-worker: failed",
b]))})},yg=function(){xg();var a=$APP.C(vg);$APP.u(a)&&(pf(a,!1),pf(vg,null));a=$APP.C(ug);$APP.u(a)&&(a.abort.call(a),pf(ug,null));Af("app","");return wg()};$APP.F.prototype.Ta=cf(2,function(){var a=this.N(null);return 0<a?new $APP.Tb(this,a-1,null):null});$APP.X.prototype.Ta=cf(1,function(){return 0<this.o?new $APP.Tb(this,this.o-1,null):null});$APP.xd.prototype.Ta=cf(0,function(){return new $APP.F([this.T,this.key],0,null)});
var zg=function zg(a){switch(arguments.length){case 0:return zg.C();case 1:return zg.g(arguments[0]);case 2:return zg.h(arguments[0],arguments[1]);case 3:return zg.j(arguments[0],arguments[1],arguments[2]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return zg.v(arguments[0],arguments[1],arguments[2],new $APP.F(c.slice(3),0,null))}};zg.C=function(){return $APP.qc};zg.g=function(a){return a};
zg.h=function(a,b){return function(){function c(l,m,n){l=b.j?b.j(l,m,n):b.call(null,l,m,n);return a.g?a.g(l):a.call(null,l)}function d(l,m){l=b.h?b.h(l,m):b.call(null,l,m);return a.g?a.g(l):a.call(null,l)}function e(l){l=b.g?b.g(l):b.call(null,l);return a.g?a.g(l):a.call(null,l)}function f(){var l=b.C?b.C():b.call(null);return a.g?a.g(l):a.call(null,l)}var h=null,k=function(){function l(n,p,q,r){var w=null;if(3<arguments.length){w=0;for(var y=Array(arguments.length-3);w<y.length;)y[w]=arguments[w+
3],++w;w=new $APP.F(y,0,null)}return m.call(this,n,p,q,w)}function m(n,p,q,r){n=$APP.Oc(b,n,p,q,r);return a.g?a.g(n):a.call(null,n)}l.I=3;l.G=function(n){var p=$APP.H(n);n=$APP.K(n);var q=$APP.H(n);n=$APP.K(n);var r=$APP.H(n);n=$APP.Bb(n);return m(p,q,r,n)};l.v=m;return l}();h=function(l,m,n,p){switch(arguments.length){case 0:return f.call(this);case 1:return e.call(this,l);case 2:return d.call(this,l,m);case 3:return c.call(this,l,m,n);default:var q=null;if(3<arguments.length){q=0;for(var r=Array(arguments.length-
3);q<r.length;)r[q]=arguments[q+3],++q;q=new $APP.F(r,0,null)}return k.v(l,m,n,q)}throw Error("Invalid arity: "+arguments.length);};h.I=3;h.G=k.G;h.C=f;h.g=e;h.h=d;h.j=c;h.v=k.v;return h}()};
zg.j=function(a,b,c){return function(){function d(m,n,p){m=c.j?c.j(m,n,p):c.call(null,m,n,p);m=b.g?b.g(m):b.call(null,m);return a.g?a.g(m):a.call(null,m)}function e(m,n){m=c.h?c.h(m,n):c.call(null,m,n);m=b.g?b.g(m):b.call(null,m);return a.g?a.g(m):a.call(null,m)}function f(m){m=c.g?c.g(m):c.call(null,m);m=b.g?b.g(m):b.call(null,m);return a.g?a.g(m):a.call(null,m)}function h(){var m=c.C?c.C():c.call(null);m=b.g?b.g(m):b.call(null,m);return a.g?a.g(m):a.call(null,m)}var k=null,l=function(){function m(p,
q,r,w){var y=null;if(3<arguments.length){y=0;for(var B=Array(arguments.length-3);y<B.length;)B[y]=arguments[y+3],++y;y=new $APP.F(B,0,null)}return n.call(this,p,q,r,y)}function n(p,q,r,w){p=$APP.Oc(c,p,q,r,w);p=b.g?b.g(p):b.call(null,p);return a.g?a.g(p):a.call(null,p)}m.I=3;m.G=function(p){var q=$APP.H(p);p=$APP.K(p);var r=$APP.H(p);p=$APP.K(p);var w=$APP.H(p);p=$APP.Bb(p);return n(q,r,w,p)};m.v=n;return m}();k=function(m,n,p,q){switch(arguments.length){case 0:return h.call(this);case 1:return f.call(this,
m);case 2:return e.call(this,m,n);case 3:return d.call(this,m,n,p);default:var r=null;if(3<arguments.length){r=0;for(var w=Array(arguments.length-3);r<w.length;)w[r]=arguments[r+3],++r;r=new $APP.F(w,0,null)}return l.v(m,n,p,r)}throw Error("Invalid arity: "+arguments.length);};k.I=3;k.G=l.G;k.C=h;k.g=f;k.h=e;k.j=d;k.v=l.v;return k}()};
zg.v=function(a,b,c,d){var e=mf($APP.V(a,$APP.V(b,$APP.V(c,d))));return function(){function f(k){var l=null;if(0<arguments.length){l=0;for(var m=Array(arguments.length-0);l<m.length;)m[l]=arguments[l+0],++l;l=new $APP.F(m,0,null)}return h.call(this,l)}function h(k){k=$APP.Mc($APP.H(e),k);for(var l=$APP.K(e);;)if(l){var m=$APP.H(l);k=m.g?m.g(k):m.call(null,k);l=$APP.K(l)}else return k}f.I=0;f.G=function(k){k=$APP.G(k);return h(k)};f.v=h;return f}()};
zg.G=function(a){var b=$APP.H(a),c=$APP.K(a);a=$APP.H(c);var d=$APP.K(c);c=$APP.H(d);d=$APP.K(d);return this.v(b,a,c,d)};zg.I=3;$APP.g=of.prototype;$APP.g.O=function(a,b){return this===b};$APP.g.tb=function(){return this.state};$APP.g.S=function(){return this.u};$APP.g.R=function(){return $APP.ea(this)};$APP.g.$=$APP.E;$APP.g.P=function(a,b,c){$APP.D(b,"#object[cljs.core.Atom ");$APP.Y(new $APP.ia(null,1,[$APP.$e,this.state],null),b,c);return $APP.D(b,"]")};
var Hf=function Hf(a){switch(arguments.length){case 2:return Hf.h(arguments[0],arguments[1]);case 3:return Hf.j(arguments[0],arguments[1],arguments[2]);case 4:return Hf.H(arguments[0],arguments[1],arguments[2],arguments[3]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return Hf.v(arguments[0],arguments[1],arguments[2],arguments[3],new $APP.F(c.slice(4),0,null))}};
Hf.h=function(a,b){if(a instanceof of){var c=a.state;b=b.g?b.g(c):b.call(null,c);a=pf(a,b)}else a=$APP.Se(a,b);return a};Hf.j=function(a,b,c){if(a instanceof of){var d=a.state;b=b.h?b.h(d,c):b.call(null,d,c);a=pf(a,b)}else a=$APP.Se(a,b,c);return a};Hf.H=function(a,b,c,d){if(a instanceof of){var e=a.state;b=b.j?b.j(e,c,d):b.call(null,e,c,d);a=pf(a,b)}else a=$APP.Se(a,b,c,d);return a};Hf.v=function(a,b,c,d,e){return a instanceof of?pf(a,$APP.Oc(b,a.state,c,d,e)):$APP.Se(a,b,c,d,e)};
Hf.G=function(a){var b=$APP.H(a),c=$APP.K(a);a=$APP.H(c);var d=$APP.K(c);c=$APP.H(d);var e=$APP.K(d);d=$APP.H(e);e=$APP.K(e);return this.v(b,a,c,d,e)};Hf.I=4;
var Rf=new $APP.W(null,"viewBox","viewBox",-469489477),Sf=new $APP.W(null,"transform","transform",1381301764),Zf=new $APP.W(null,"r","r",-471384190),ig=new $APP.W(null,"stroke-width","stroke-width",716836435),eg=new $APP.W(null,"d","d",1972142424),$f=new $APP.W(null,"fill","fill",883462889),Mf=new $APP.W(null,"class","class",-2030961996),Yf=new $APP.W(null,"cy","cy",755331060),Vf=new $APP.W(null,"speed","speed",1257663751),Xf=new $APP.W(null,"cx","cx",1272694324),Df=new $APP.W(null,"data-value","data-value",
-1897915206),mg=new $APP.W(null,"orbits","orbits",820507030),dg=new $APP.W(null,"stroke","stroke",1741823555),Lf=new $APP.W(null,"id","id",-1388402092),Of=new $APP.W(null,"svg","svg",856789142),rg=new $APP.W(null,"phase","phase",575722892),Pf=new $APP.W(null,"scene","scene",1523800415),lg=new $APP.W(null,"balls","balls",1987549674),Qf=new $APP.xb("relax.scene","on-resize","relax.scene/on-resize",827241716,null),kg=new $APP.W(null,"start","start",-355208981);var hg=function hg(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return hg.v(arguments[0],1<c.length?new $APP.F(c.slice(1),0,null):null)};hg.v=function(a,b){b=$APP.G(b);for(var c=null,d=0,e=0;;)if(e<d){var f=c.K(null,e),h=a;h.appendChild.call(h,f);e+=1}else if(b=$APP.G(b))$APP.bc(b)?(d=$APP.hb(b),b=$APP.ib(b),c=d,d=$APP.M(d)):(c=$APP.H(b),d=a,d.appendChild.call(d,c),b=$APP.K(b),c=null,d=0),e=0;else break;return a};hg.I=1;
hg.G=function(a){var b=$APP.H(a);a=$APP.K(a);return this.v(b,a)};var kf=function kf(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return kf.v(arguments[0],1<c.length?new $APP.F(c.slice(1),0,null):null)};
kf.v=function(a,b){var c=document;a=c.createElementNS.call(c,"http://www.w3.org/2000/svg",a);b=$APP.Zb($APP.H(b))?new $APP.X(null,2,5,$APP.Ae,[$APP.H(b),$APP.Bb(b)],null):new $APP.X(null,2,5,$APP.Ae,[null,b],null);c=$APP.T(b,0,null);b=$APP.T(b,1,null);c=$APP.G(c);for(var d=null,e=0,f=0;;)if(f<e){var h=d.K(null,f),k=$APP.T(h,0,null);h=$APP.T(h,1,null);qf(a,$APP.Q([k,h]));f+=1}else if(c=$APP.G(c))$APP.bc(c)?(e=$APP.hb(c),c=$APP.ib(c),d=e,e=$APP.M(e)):(e=$APP.H(c),d=$APP.T(e,0,null),e=$APP.T(e,1,null),
qf(a,$APP.Q([d,e])),c=$APP.K(c),d=null,e=0),f=0;else break;return $APP.Yb($APP.H(b))?$APP.Nc(hg,a,$APP.H(b)):$APP.Nc(hg,a,b)};kf.I=1;kf.G=function(a){var b=$APP.H(a);a=$APP.K(a);return this.v(b,a)};var jg=lf("svg"),Uf=lf("g"),Wf=lf("circle"),cg=lf("path");var uf={},sf={},tf=[];vf.cache={};vf.resolve=function(a){return a};var Ag;Ag=vf(0,{});var Gf=new of(!1),If=new of(!1),Jf=new of(!1);var sg=$APP.$c(function(a){return new Ag({src:a})},$APP.bf),hf=$APP.M(sg),og=function(){var a=zg.h(xf(),wf(new $APP.X(null,2,5,$APP.Ae,[0,90],null),new $APP.X(null,2,5,$APP.Ae,[100,0],null)));return function(b){return a(90<b&&180>b?b-90:270<b&&360>b?b-270:100)}}(),qg=wf(new $APP.X(null,2,5,$APP.Ae,[0,100],null),new $APP.X(null,2,5,$APP.Ae,[40,100],null)),pg=wf(new $APP.X(null,2,5,$APP.Ae,[0,100],null),new $APP.X(null,2,5,$APP.Ae,[20,60],null)),ag=wf(new $APP.X(null,2,5,$APP.Ae,[0,hf],null),new $APP.X(null,
2,5,$APP.Ae,[200,300],null));var gg,Bg=window.performance;gg=Bg.now.call(Bg);var ug=new of(null),vg=new of(null),Cg=["relax","app","run"],Dg=$APP.Ne;Cg[0]in Dg||"undefined"==typeof Dg.execScript||Dg.execScript("var "+Cg[0]);for(var Eg;Cg.length&&(Eg=Cg.shift());)Cg.length||void 0===yg?Dg=Dg[Eg]&&Dg[Eg]!==Object.prototype[Eg]?Dg[Eg]:Dg[Eg]={}:Dg[Eg]=yg;
}).call(this);