(function(){
'use strict';var rf=function(a,b){return $APP.aa[a]=b},sf=function(){},tf=function(a){if(null!=a&&null!=a.Ta)a=a.Ta(a);else{var b=tf[$APP.r(null==a?null:a)];if(null!=b)a=b.g?b.g(a):b.call(null,a);else if(b=tf._,null!=b)a=b.g?b.g(a):b.call(null,a);else throw $APP.y("IReversible.-rseq",a);}return a},uf=function(a,b){if(null!=$APP.nf&&null!=$APP.nf.wb)$APP.nf.wb($APP.nf,a,b);else{var c=uf[$APP.r(null==$APP.nf?null:$APP.nf)];if(null!=c)c.j?c.j($APP.nf,a,b):c.call(null,$APP.nf,a,b);else if(c=uf._,null!=
c)c.j?c.j($APP.nf,a,b):c.call(null,$APP.nf,a,b);else throw $APP.y("IWatchable.-add-watch",$APP.nf);}},vf=function(a,b){if(null!=a&&null!=a.Qb)a=a.Qb(a,b);else{var c=vf[$APP.r(null==a?null:a)];if(null!=c)a=c.h?c.h(a,b):c.call(null,a,b);else if(c=vf._,null!=c)a=c.h?c.h(a,b):c.call(null,a,b);else throw $APP.y("IReset.-reset!",a);}return a},wf=function(a){return a+1},xf=function(a){if(null==$APP.qa)throw Error("No *print-fn* fn set for evaluation environment");$APP.qa.call(null,a)},yf=function(a){for(var b=
$APP.rc;;)if(a=$APP.G(a)){var c=$APP.H(a);c=b.g?b.g(c):b.call(null,c);if($APP.v(c))return c;a=$APP.J(a)}else return null},Af=function(){var a=zf;return 0>=a?$APP.I:$APP.ec(0)&&$APP.ec(a)&&$APP.ec(1)?new $APP.se(null,0,a,1,null,null,null):new $APP.te(null,0,a,1,null,null,null)},Cf=function(a){var b=Bf;return function(){function c(l,m,n){return b.D?b.D(a,l,m,n):b.call(null,a,l,m,n)}function d(l,m){return b.j?b.j(a,l,m):b.call(null,a,l,m)}function e(l){return b.h?b.h(a,l):b.call(null,a,l)}function f(){return b.g?
b.g(a):b.call(null,a)}var h=null,k=function(){function l(n,p,q,u){var x=null;if(3<arguments.length){x=0;for(var z=Array(arguments.length-3);x<z.length;)z[x]=arguments[x+3],++x;x=new $APP.F(z,0,null)}return m.call(this,n,p,q,x)}function m(n,p,q,u){return $APP.Qc(b,a,n,p,q,$APP.Q([u]))}l.I=3;l.G=function(n){var p=$APP.H(n);n=$APP.J(n);var q=$APP.H(n);n=$APP.J(n);var u=$APP.H(n);n=$APP.Bb(n);return m(p,q,u,n)};l.v=m;return l}();h=function(l,m,n,p){switch(arguments.length){case 0:return f.call(this);
case 1:return e.call(this,l);case 2:return d.call(this,l,m);case 3:return c.call(this,l,m,n);default:var q=null;if(3<arguments.length){q=0;for(var u=Array(arguments.length-3);q<u.length;)u[q]=arguments[q+3],++q;q=new $APP.F(u,0,null)}return k.v(l,m,n,q)}throw Error("Invalid arity: "+arguments.length);};h.I=3;h.G=k.G;h.B=f;h.g=e;h.h=d;h.j=c;h.v=k.v;return h}()},Df=function(a){return(null!=a?a.l&134217728||$APP.D===a.mc||(a.l?0:$APP.w(sf,a)):$APP.w(sf,a))?(a=tf(a))?a:$APP.I:$APP.kc($APP.Zc,$APP.I,a)},
Ef=function(a){var b=$APP.He.j($APP.na(),$APP.ja,!1);xf($APP.Je(a,b));$APP.v($APP.oa)?(a=$APP.na(),xf("\n"),a=($APP.U.h(a,$APP.ia),null)):a=null;return a},Ff=function(a,b){if(a instanceof $APP.Yc){var c=a.ac;if(null!=c&&!$APP.v(c.g?c.g(b):c.call(null,b)))throw Error("Validator rejected reference state");c=a.state;a.state=b;if(null!=a.qb)a:for(var d=$APP.G(a.qb),e=null,f=0,h=0;;)if(h<f){var k=e.K(null,h),l=$APP.S(k,0,null);k=$APP.S(k,1,null);k.D?k.D(l,a,c,b):k.call(null,l,a,c,b);h+=1}else if(d=$APP.G(d))$APP.bc(d)?
(e=$APP.hb(d),d=$APP.ib(d),l=e,f=$APP.M(e),e=l):(e=$APP.H(d),l=$APP.S(e,0,null),k=$APP.S(e,1,null),k.D?k.D(l,a,c,b):k.call(null,l,a,c,b),d=$APP.J(d),e=null,f=0),h=0;else break a;return b}return vf(a,b)},If=function(a){null==Gf&&(Gf=new $APP.Yc(0));var b=$APP.Ke.g([$APP.A.g("G__"),$APP.A.g(Hf.h(Gf,wf))].join(""));uf(b,a)},Jf=function(a){this.f=a;this.value=null;this.l=2147516416;this.C=1},Kf=function(a,b,c){If(function(d,e,f,h){d=$APP.U.h(f,a);h=$APP.U.h(h,a);return $APP.N.h(d,h)?null:$APP.Oc(b,h,
c)})},Lf=function(a){for(var b=[],c=arguments.length,d=0;;)if(d<c)b.push(arguments[d]),d+=1;else break;Kf(arguments[0],arguments[1],2<b.length?new $APP.F(b.slice(2),0,null):null)},Mf=function(a,b){var c=$APP.S(a,0,null);a=$APP.S(a,1,null);var d=$APP.S(b,0,null);b=$APP.S(b,1,null);var e=a-c,f=b-d;return function(h){return d+(h-c)/e*f}},Nf=function(){return function(a){return 0>a?0:100<a?100:a}},Of=function(a){if("string"===typeof a){var b=document;return b.getElementById.call(b,a)}return a},Qf=function(){var a=
$APP.Q([Pf,"none"]),b=Of("fullscreen"),c=$APP.G(a);$APP.H(c);c=$APP.J(c);$APP.H(c);for($APP.J(c);;){c=$APP.G(a);a=$APP.H(c);c=$APP.J(c);var d=$APP.H(c),e=$APP.J(c);c=d;d=e;e=b;e.setAttribute.call(e,$APP.pe(a),$APP.A.g(c));if($APP.G(d))a=d;else break}},Rf=function(a){a=Of(a);var b=a.classList;b.add.call(b,"active");return a},Sf=function(a){a=Of(a);var b=a.classList;b.remove.call(b,"active");return a},Tf=function(a,b,c){a=Of(a);a.addEventListener.call(a,$APP.pe(b),c,null)},Uf=function(a,b){$APP.v($APP.gf.g($APP.Na($APP.nf)))&&
(a=$APP.Qb($APP.qf,a),a.stereo.call(a,b),a.play.call(a))},Vf=function(a){return $APP.v(a)?Rf("sound"):Sf("sound")},Wf=function(a){if($APP.v(a)){Rf("fullscreen");a=function(){var c=Of("wrapper");return c.requestFullscreen.call(c)}();var b=a.then}else Sf("fullscreen"),a=function(){var c=document;return c.exitFullscreen.call(c)}(),b=a.then;return b.call(a,function(){return Ef($APP.Q(["fullscreen: success"]))},function(){return Ef($APP.Q(["fullscreen: rejected"]))})},$f=function(){var a=null!=function(){var c=
document;if(null!=c)return c.exitFullscreen}(),b=null!=function(){var c=document;if(null!=c)return c.fullscreenElement}();a||Qf();a&&Lf(Xf,Wf);Hf.j($APP.nf,Yf,new $APP.t(null,2,[Zf,a,Xf,b],null))},ag=function(a,b){var c=$APP.G(b);$APP.H(c);c=$APP.J(c);$APP.H(c);for($APP.J(c);;){c=$APP.G(b);b=$APP.H(c);c=$APP.J(c);var d=$APP.H(c),e=$APP.J(c);c=d;d=e;e=a;e.setAttributeNS.call(e,null,$APP.pe(b),$APP.A.g(c));if(d)b=d;else return a}},bg=function(a,b){return a.getAttributeNS.call(a,null,$APP.pe(b))},kg=
function(a){return cg(new $APP.t(null,1,[dg,180*(20+.5*a)/3E5],null),eg(new $APP.t(null,4,[fg,100+1E3/(zf+2)*a,gg,0,hg,15,ig,["hsl(",$APP.A.g(jg(a))," 100% 50%)"].join("")],null)))},og=function(a){a=100+1E3/(zf+2)*a;return lg(new $APP.t(null,2,[mg,"hsl(0 0% 30%)",ng,["M 0,",$APP.A.g(-a)," A ",$APP.A.g(a)," ",$APP.A.g(a)," 180 1 1 0,",$APP.A.g(a)].join("")],null))},wg=function(a){a=$APP.Qb(pg,a);var b=$APP.Vc(a),c=$APP.U.h(b,qg);a=$APP.U.h(b,rg);b=$APP.U.h(b,sg);c=c.B?c.B():c.call(null);Ff(tg,new $APP.t(null,
3,[ug,c,rg,a,sg,b],null));b=Of("app");(null!=b?b:{}).textContent="";var d=$APP.Q([vg.g(c)]);b=Of(b);d=$APP.G(d);for(var e=null,f=0,h=0;;)if(h<f){var k=e.K(null,h),l=b;l.append.call(l,k);h+=1}else if(d=$APP.G(d))$APP.bc(d)?(f=$APP.hb(d),d=$APP.ib(d),e=f,f=$APP.M(f)):(e=$APP.H(d),f=b,f.append.call(f,e),d=$APP.J(d),e=null,f=0),h=0;else break;return a.h?a.h(c,null):a.call(null,c,null)},xg=function(a){var b=$APP.Na(tg),c=$APP.Vc(b);b=$APP.U.h(c,rg);c=$APP.U.h(c,ug);return b.h?b.h(c,a):b.call(null,c,a)},
zg=function(){return Hf.D($APP.nf,yg,$APP.gf,$APP.ta)},Ag=function(){return Hf.D($APP.nf,yg,Xf,$APP.ta)},Cg=function(a){return function(){return Hf.v($APP.nf,yg,Bg,function(b,c){b+=c;return b>=$APP.M(pg)?0:0>b?$APP.M(pg)-1:b},$APP.Q([a]))}},Fg=function(a){var b=function(){var c=null!=a?a.code:void 0;switch(c){case "ArrowUp":return Ag;case "ArrowRight":return Dg;case "ArrowLeft":return Eg;case "ArrowDown":return zg;default:return null}}();$APP.v(b)&&(a.preventDefault.call(a),b.B?b.B():b.call(null));
return null},Hg=function(){return $APP.Na(Gg)};$APP.Yc.prototype.wb=rf(3,function(a,b,c){this.qb=$APP.He.j(this.qb,b,c);return this});$APP.F.prototype.Ta=rf(2,function(){var a=this.O(null);return 0<a?new $APP.Tb(this,a-1,null):null});$APP.X.prototype.Ta=rf(1,function(){return 0<this.o?new $APP.Tb(this,this.o-1,null):null});$APP.zd.prototype.Ta=rf(0,function(){return new $APP.F([this.T,this.key],0,null)});
var Yf=function Yf(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return Yf.v(0<c.length?new $APP.F(c.slice(0),0,null):null)};Yf.v=function(a){return $APP.v(yf(a))?$APP.oc(function(b,c){return $APP.Zc.h($APP.v(b)?b:$APP.Uc,c)},a):null};Yf.I=0;Yf.G=function(a){return this.v($APP.G(a))};
var yg=function yg(a){switch(arguments.length){case 3:return yg.j(arguments[0],arguments[1],arguments[2]);case 4:return yg.D(arguments[0],arguments[1],arguments[2],arguments[3]);case 5:return yg.ga(arguments[0],arguments[1],arguments[2],arguments[3],arguments[4]);case 6:return yg.wa(arguments[0],arguments[1],arguments[2],arguments[3],arguments[4],arguments[5]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return yg.v(arguments[0],arguments[1],arguments[2],
arguments[3],arguments[4],arguments[5],new $APP.F(c.slice(6),0,null))}};yg.j=function(a,b,c){var d=$APP.He.j,e=$APP.U.h(a,b);c=c.g?c.g(e):c.call(null,e);return d.call($APP.He,a,b,c)};yg.D=function(a,b,c,d){var e=$APP.He.j,f=$APP.U.h(a,b);c=c.h?c.h(f,d):c.call(null,f,d);return e.call($APP.He,a,b,c)};yg.ga=function(a,b,c,d,e){var f=$APP.He.j,h=$APP.U.h(a,b);c=c.j?c.j(h,d,e):c.call(null,h,d,e);return f.call($APP.He,a,b,c)};
yg.wa=function(a,b,c,d,e,f){var h=$APP.He.j,k=$APP.U.h(a,b);c=c.D?c.D(k,d,e,f):c.call(null,k,d,e,f);return h.call($APP.He,a,b,c)};yg.v=function(a,b,c,d,e,f,h){return $APP.He.j(a,b,$APP.Qc(c,$APP.U.h(a,b),d,e,f,$APP.Q([h])))};yg.G=function(a){var b=$APP.H(a),c=$APP.J(a);a=$APP.H(c);var d=$APP.J(c);c=$APP.H(d);var e=$APP.J(d);d=$APP.H(e);var f=$APP.J(e);e=$APP.H(f);var h=$APP.J(f);f=$APP.H(h);h=$APP.J(h);return this.v(b,a,c,d,e,f,h)};yg.I=6;
var Ig=function Ig(a){switch(arguments.length){case 0:return Ig.B();case 1:return Ig.g(arguments[0]);case 2:return Ig.h(arguments[0],arguments[1]);case 3:return Ig.j(arguments[0],arguments[1],arguments[2]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return Ig.v(arguments[0],arguments[1],arguments[2],new $APP.F(c.slice(3),0,null))}};Ig.B=function(){return $APP.rc};Ig.g=function(a){return a};
Ig.h=function(a,b){return function(){function c(l,m,n){l=b.j?b.j(l,m,n):b.call(null,l,m,n);return a.g?a.g(l):a.call(null,l)}function d(l,m){l=b.h?b.h(l,m):b.call(null,l,m);return a.g?a.g(l):a.call(null,l)}function e(l){l=b.g?b.g(l):b.call(null,l);return a.g?a.g(l):a.call(null,l)}function f(){var l=b.B?b.B():b.call(null);return a.g?a.g(l):a.call(null,l)}var h=null,k=function(){function l(n,p,q,u){var x=null;if(3<arguments.length){x=0;for(var z=Array(arguments.length-3);x<z.length;)z[x]=arguments[x+
3],++x;x=new $APP.F(z,0,null)}return m.call(this,n,p,q,x)}function m(n,p,q,u){n=$APP.Pc(b,n,p,q,u);return a.g?a.g(n):a.call(null,n)}l.I=3;l.G=function(n){var p=$APP.H(n);n=$APP.J(n);var q=$APP.H(n);n=$APP.J(n);var u=$APP.H(n);n=$APP.Bb(n);return m(p,q,u,n)};l.v=m;return l}();h=function(l,m,n,p){switch(arguments.length){case 0:return f.call(this);case 1:return e.call(this,l);case 2:return d.call(this,l,m);case 3:return c.call(this,l,m,n);default:var q=null;if(3<arguments.length){q=0;for(var u=Array(arguments.length-
3);q<u.length;)u[q]=arguments[q+3],++q;q=new $APP.F(u,0,null)}return k.v(l,m,n,q)}throw Error("Invalid arity: "+arguments.length);};h.I=3;h.G=k.G;h.B=f;h.g=e;h.h=d;h.j=c;h.v=k.v;return h}()};
Ig.j=function(a,b,c){return function(){function d(m,n,p){m=c.j?c.j(m,n,p):c.call(null,m,n,p);m=b.g?b.g(m):b.call(null,m);return a.g?a.g(m):a.call(null,m)}function e(m,n){m=c.h?c.h(m,n):c.call(null,m,n);m=b.g?b.g(m):b.call(null,m);return a.g?a.g(m):a.call(null,m)}function f(m){m=c.g?c.g(m):c.call(null,m);m=b.g?b.g(m):b.call(null,m);return a.g?a.g(m):a.call(null,m)}function h(){var m=c.B?c.B():c.call(null);m=b.g?b.g(m):b.call(null,m);return a.g?a.g(m):a.call(null,m)}var k=null,l=function(){function m(p,
q,u,x){var z=null;if(3<arguments.length){z=0;for(var E=Array(arguments.length-3);z<E.length;)E[z]=arguments[z+3],++z;z=new $APP.F(E,0,null)}return n.call(this,p,q,u,z)}function n(p,q,u,x){p=$APP.Pc(c,p,q,u,x);p=b.g?b.g(p):b.call(null,p);return a.g?a.g(p):a.call(null,p)}m.I=3;m.G=function(p){var q=$APP.H(p);p=$APP.J(p);var u=$APP.H(p);p=$APP.J(p);var x=$APP.H(p);p=$APP.Bb(p);return n(q,u,x,p)};m.v=n;return m}();k=function(m,n,p,q){switch(arguments.length){case 0:return h.call(this);case 1:return f.call(this,
m);case 2:return e.call(this,m,n);case 3:return d.call(this,m,n,p);default:var u=null;if(3<arguments.length){u=0;for(var x=Array(arguments.length-3);u<x.length;)x[u]=arguments[u+3],++u;u=new $APP.F(x,0,null)}return l.v(m,n,p,u)}throw Error("Invalid arity: "+arguments.length);};k.I=3;k.G=l.G;k.B=h;k.g=f;k.h=e;k.j=d;k.v=l.v;return k}()};
Ig.v=function(a,b,c,d){var e=Df($APP.V(a,$APP.V(b,$APP.V(c,d))));return function(){function f(k){var l=null;if(0<arguments.length){l=0;for(var m=Array(arguments.length-0);l<m.length;)m[l]=arguments[l+0],++l;l=new $APP.F(m,0,null)}return h.call(this,l)}function h(k){k=$APP.Nc($APP.H(e),k);for(var l=$APP.J(e);;)if(l){var m=$APP.H(l);k=m.g?m.g(k):m.call(null,k);l=$APP.J(l)}else return k}f.I=0;f.G=function(k){k=$APP.G(k);return h(k)};f.v=h;return f}()};
Ig.G=function(a){var b=$APP.H(a),c=$APP.J(a);a=$APP.H(c);var d=$APP.J(c);c=$APP.H(d);d=$APP.J(d);return this.v(b,a,c,d)};Ig.I=3;
var Hf=function Hf(a){switch(arguments.length){case 2:return Hf.h(arguments[0],arguments[1]);case 3:return Hf.j(arguments[0],arguments[1],arguments[2]);case 4:return Hf.D(arguments[0],arguments[1],arguments[2],arguments[3]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return Hf.v(arguments[0],arguments[1],arguments[2],arguments[3],new $APP.F(c.slice(4),0,null))}};
Hf.h=function(a,b){if(a instanceof $APP.Yc){var c=a.state;b=b.g?b.g(c):b.call(null,c);a=Ff(a,b)}else a=$APP.Xe(a,b);return a};Hf.j=function(a,b,c){if(a instanceof $APP.Yc){var d=a.state;b=b.h?b.h(d,c):b.call(null,d,c);a=Ff(a,b)}else a=$APP.Xe(a,b,c);return a};Hf.D=function(a,b,c,d){if(a instanceof $APP.Yc){var e=a.state;b=b.j?b.j(e,c,d):b.call(null,e,c,d);a=Ff(a,b)}else a=$APP.Xe(a,b,c,d);return a};
Hf.v=function(a,b,c,d,e){return a instanceof $APP.Yc?Ff(a,$APP.Pc(b,a.state,c,d,e)):$APP.Xe(a,b,c,d,e)};Hf.G=function(a){var b=$APP.H(a),c=$APP.J(a);a=$APP.H(c);var d=$APP.J(c);c=$APP.H(d);var e=$APP.J(d);d=$APP.H(e);e=$APP.J(e);return this.v(b,a,c,d,e)};Hf.I=4;var Gf=null;Jf.prototype.nb=function(){$APP.v(this.f)&&(this.value=this.f.B?this.f.B():this.f.call(null),this.f=null);return this.value};
Jf.prototype.M=function(a,b,c){$APP.C(b,"#object[cljs.core.Delay ");$APP.Y(new $APP.t(null,2,[$APP.hf,null==this.f?$APP.mf:$APP.kf,$APP.ff,this.value],null),b,c);return $APP.C(b,"]")};
var Jg=new $APP.W(null,"transform","transform",1381301764),hg=new $APP.W(null,"r","r",-471384190),sg=new $APP.W(null,"on-tick","on-tick",-56973396),ng=new $APP.W(null,"d","d",1972142424),Kg=new $APP.W(null,"click","click",1912301393),gg=new $APP.W(null,"cy","cy",755331060),rg=new $APP.W(null,"on-resize","on-resize",-2005528129),dg=new $APP.W(null,"speed","speed",1257663751),fg=new $APP.W(null,"cx","cx",1272694324),Lg=new $APP.xb("relax.pendulum","on-resize","relax.pendulum/on-resize",413697598,null),
Pf=new $APP.W(null,"display","display",242065432),ug=new $APP.W(null,"scene","scene",1523800415),Mg=new $APP.W(null,"viewBox","viewBox",-469489477),Ng=new $APP.W(null,"keydown","keydown",-629268186),Og=new $APP.W(null,"stroke-width","stroke-width",716836435),Xf=new $APP.W(null,"is-fullscreen?","is-fullscreen?",972486782),ig=new $APP.W(null,"fill","fill",883462889),vg=new $APP.W(null,"elem","elem",618631056),qg=new $APP.W(null,"create-scene","create-scene",1581407535),Zf=new $APP.W(null,"can-fullscreen?",
"can-fullscreen?",-1592427507),Pg=new $APP.W(null,"orbits","orbits",820507030),mg=new $APP.W(null,"stroke","stroke",1741823555),Bg=new $APP.W(null,"scene-id","scene-id",2130439689),Qg=new $APP.W(null,"phase","phase",575722892),Rg=new $APP.W(null,"balls","balls",1987549674),Sg=new $APP.W(null,"resize","resize",297367086);var Tg=function Tg(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return Tg.v(arguments[0],1<c.length?new $APP.F(c.slice(1),0,null):null)};Tg.v=function(a,b){b=$APP.G(b);for(var c=null,d=0,e=0;;)if(e<d){var f=c.K(null,e),h=a;h.appendChild.call(h,f);e+=1}else if(b=$APP.G(b))$APP.bc(b)?(d=$APP.hb(b),b=$APP.ib(b),c=d,d=$APP.M(d)):(c=$APP.H(b),d=a,d.appendChild.call(d,c),b=$APP.J(b),c=null,d=0),e=0;else break;return a};Tg.I=1;
Tg.G=function(a){var b=$APP.H(a);a=$APP.J(a);return this.v(b,a)};var Bf=function Bf(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return Bf.v(arguments[0],1<c.length?new $APP.F(c.slice(1),0,null):null)};
Bf.v=function(a,b){var c=document;a=c.createElementNS.call(c,"http://www.w3.org/2000/svg",a);b=$APP.Zb($APP.H(b))?new $APP.X(null,2,5,$APP.Ce,[$APP.H(b),$APP.Bb(b)],null):new $APP.X(null,2,5,$APP.Ce,[null,b],null);c=$APP.S(b,0,null);b=$APP.S(b,1,null);c=$APP.G(c);for(var d=null,e=0,f=0;;)if(f<e){var h=d.K(null,f),k=$APP.S(h,0,null);h=$APP.S(h,1,null);ag(a,$APP.Q([k,h]));f+=1}else if(c=$APP.G(c))$APP.bc(c)?(e=$APP.hb(c),c=$APP.ib(c),d=e,e=$APP.M(e)):(e=$APP.H(c),d=$APP.S(e,0,null),e=$APP.S(e,1,null),
ag(a,$APP.Q([d,e])),c=$APP.J(c),d=null,e=0),f=0;else break;return $APP.Yb($APP.H(b))?$APP.Oc(Tg,a,$APP.H(b)):$APP.Oc(Tg,a,b)};Bf.I=1;Bf.G=function(a){var b=$APP.H(a);a=$APP.J(a);return this.v(b,a)};var Ug=Cf("svg"),cg=Cf("g"),eg=Cf("circle"),lg=Cf("path");var zf=$APP.M($APP.qf),Vg=function(){var a=Ig.h(Nf(),Mf(new $APP.X(null,2,5,$APP.Ce,[0,90],null),new $APP.X(null,2,5,$APP.Ce,[100,0],null)));return function(b){return a(90<b&&180>b?b-90:270<b&&360>b?b-270:100)}}(),Wg=Mf(new $APP.X(null,2,5,$APP.Ce,[0,100],null),new $APP.X(null,2,5,$APP.Ce,[40,100],null)),Xg=Mf(new $APP.X(null,2,5,$APP.Ce,[0,100],null),new $APP.X(null,2,5,$APP.Ce,[20,60],null)),jg=Mf(new $APP.X(null,2,5,$APP.Ce,[0,zf],null),new $APP.X(null,2,5,$APP.Ce,[200,300],null));var pg=new $APP.X(null,1,5,$APP.Ce,[new $APP.t(null,3,[qg,function(){var a=$APP.bd(kg,Af()),b=$APP.bd(og,Af()),c=Tg.v(Tg.v(cg(),$APP.Q([cg(new $APP.t(null,2,[Og,1,ig,"none"],null),b)])),$APP.Q([cg(new $APP.t(null,1,[Og,2],null),a)]));return new $APP.t(null,4,[vg,Ug(new $APP.t(null,2,[$APP.jf,"ar-2-1",Mg,"0 0 0 0"],null),c),ug,c,Rg,a,Pg,b],null)},rg,function(a){var b=$APP.Vc(a);a=$APP.U.h(b,vg);b=$APP.U.h(b,ug);var c=null!=a?a.clientWidth:void 0;var d=null!=a?a.clientHeight:void 0;var e=c/2E3;var f=
d/1E3;e=e<f?e:f;console.log(Lg,c,"x",d,"\x3d\x3e",e);ag(a,$APP.Q([Mg,["0 0 ",$APP.A.g(c)," ",$APP.A.g(d)].join("")]));return ag(b,$APP.Q([Jg,["translate(",$APP.A.g(.5*c)," ",$APP.A.g(d),") scale(",$APP.A.g(e),")rotate(-90)"].join("")]))},sg,function(a,b){var c=$APP.Vc(a);a=$APP.U.h(c,Rg);c=$APP.U.h(c,Pg);for(var d=$APP.G(Af()),e=null,f=0,h=0;;)if(h<f){var k=e.K(null,h),l=$APP.Qb(a,k),m=$APP.Qb(c,k),n=parseFloat(bg(l,dg)),p=(b*n%360+360)%360;n=90<p&&270>p?"d":"r";var q=Vg(p);ag(m,$APP.Q([mg,["hsl(0 0% ",
$APP.A.g(Xg(q)),"%)"].join("")]));ag(l,$APP.Q([Jg,["rotate(",$APP.A.g(90>p?p:270>p?90-(p-90):-90+(p-270)),")"].join(""),mg,["hsl(0 0% ",$APP.A.g(Wg(q)),"%)"].join("")]));m=bg(l,Qg);$APP.N.h(m,n)||(ag(l,$APP.Q([Qg,n])),Uf(k,$APP.N.h(n,"r")?-.9:.9));h+=1}else if(k=$APP.G(d))d=k,$APP.bc(d)?(e=$APP.hb(d),d=$APP.ib(d),k=e,f=$APP.M(e),e=k):(k=$APP.H(d),e=$APP.Qb(a,k),f=$APP.Qb(c,k),h=parseFloat(bg(e,dg)),l=(b*h%360+360)%360,h=90<l&&270>l?"d":"r",m=Vg(l),ag(f,$APP.Q([mg,["hsl(0 0% ",$APP.A.g(Xg(m)),"%)"].join("")])),
ag(e,$APP.Q([Jg,["rotate(",$APP.A.g(90>l?l:270>l?90-(l-90):-90+(l-270)),")"].join(""),mg,["hsl(0 0% ",$APP.A.g(Wg(m)),"%)"].join("")])),f=bg(e,Qg),$APP.N.h(f,h)||(ag(e,$APP.Q([Qg,h])),Uf(k,$APP.N.h(h,"r")?-.9:.9)),d=$APP.J(d),e=null,f=0),h=0;else return null}],null)],null),tg=new $APP.Yc(null);var Eg=Cg(-1),Dg=Cg(1);var Gg=new Jf(function(){if(0!=function(){var c=window;c=null!=c?c.location:void 0;if(null!=c)return c.host}().lastIndexOf("localhost",0)){Ef($APP.Q(["init: registering worker..."]));var a=function(){var c=function(){var d=navigator.serviceWorker;return d.register.call(d,"worker.js",{scope:"./"})}();return c.then.call(c,function(){return Ef($APP.Q(["init: worker registered"]))})}();a["catch"].call(a,function(c){return Ef($APP.Q(["init: worker failed",c]))})}Ef($APP.Q(["init: init modules"]));Lf($APP.gf,
Vf);Hf.D($APP.nf,$APP.He,$APP.gf,!1);$f();Tf("fullscreen",Kg,Ag);Tf("sound",Kg,zg);Tf("prev",Kg,Eg);Tf("next",Kg,Dg);Tf(window,Ng,Fg);Tf(window,Sg,xg);Lf(Bg,wg);Hf.D($APP.nf,$APP.He,Bg,0);Ef($APP.Q(["init: animation"]));var b=function(){var c=window.performance;return c.now.call(c)}();a=window;return a.requestAnimationFrame.call(a,function e(d){d-=b;var f=$APP.Na(tg),h=$APP.Vc(f);f=$APP.U.h(h,sg);h=$APP.U.h(h,ug);f.h?f.h(h,d):f.call(null,h,d);d=window;return d.requestAnimationFrame.call(d,e)})}),
Yg=["relax","app","run"],Zg=$APP.Re;Yg[0]in Zg||"undefined"==typeof Zg.execScript||Zg.execScript("var "+Yg[0]);for(var $g;Yg.length&&($g=Yg.shift());)Yg.length||void 0===Hg?Zg=Zg[$g]&&Zg[$g]!==Object.prototype[$g]?Zg[$g]:Zg[$g]={}:Zg[$g]=Hg;
}).call(this);