importScripts("shared.js");
(function(){
'use strict';var ai=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b},bi=function(){},ci=function(){},di=function(a){if(null!=a&&null!=a.Rb)a=a.Rb(a);else{var b=di[$APP.t(null==a?null:a)];if(null!=b)a=b.g?b.g(a):b.call(null,a);else if(b=di._,null!=b)a=b.g?b.g(a):b.call(null,a);else throw $APP.z("IEncodeJS.-clj-\x3ejs",a);}return a},ei=function(a,b){return(null!=a?$APP.C===a.Qb||(a.ec?0:$APP.w(ci,a)):$APP.w(ci,a))?di(a):"string"===typeof a||"number"===typeof a||a instanceof $APP.X||
a instanceof $APP.Kb?b.g?b.g(a):b.call(null,a):$APP.Ze($APP.R([a]),$APP.wa())},fi=function(a){if(null!=a&&null!=a.Kb)a=a.Kb(a);else{var b=fi[$APP.t(null==a?null:a)];if(null!=b)a=b.g?b.g(a):b.call(null,a);else if(b=fi._,null!=b)a=b.g?b.g(a):b.call(null,a);else throw $APP.z("IState.-rejected?",a);}return a},gi=function(a){if(null!=a&&null!=a.Jb)a=a.Jb(a);else{var b=gi[$APP.t(null==a?null:a)];if(null!=b)a=b.g?b.g(a):b.call(null,a);else if(b=gi._,null!=b)a=b.g?b.g(a):b.call(null,a);else throw $APP.z("IState.-pending?",
a);}return a},hi=function(a){if(null!=a&&null!=a.qb)a=a.qb(a);else{var b=hi[$APP.t(null==a?null:a)];if(null!=b)a=b.g?b.g(a):b.call(null,a);else if(b=hi._,null!=b)a=b.g?b.g(a):b.call(null,a);else throw $APP.z("IPromiseFactory.-promise",a);}return a},ii=function(a){if(null!=a&&null!=a.Eb)a=a.Eb(a);else{var b=ii[$APP.t(null==a?null:a)];if(null!=b)a=b.g?b.g(a):b.call(null,a);else if(b=ii._,null!=b)a=b.g?b.g(a):b.call(null,a);else throw $APP.z("ICancellable.-cancelled?",a);}return a},ni=function(a,b,c){a[ji]!==
b&&a[ji]===ki&&(a[ji]=b,a[li]=c,mi(a))},ri=function(a,b,c){c?a.complete(null,c):a.type===oi?a.complete(b,null):a.type===pi?b instanceof qi?b.handle((d,e)=>{ri(a,d,e)}):ai(b)&&"function"===typeof b.then?b.then(d=>{ri(a,d,null)},d=>{ri(a,null,d)}):a.complete(b,null):a.type===si?b instanceof qi?b.handle((d,e)=>{a.complete(d,e)}):ai(b)&&"function"===typeof b.then?b.then(d=>{a.complete(d,null)},d=>{a.complete(null,d)}):a.complete(null,new TypeError("expected thenable")):a.complete(null,new TypeError("internal: invalid resolve type"))},
mi=function(a){if(0!==a[ti].length)for(var b=a[ji],c=a[li],d,e,f;a[ti].length;){d=a[ti].shift();try{b===ui?e=d.resolve(c):b===vi?e=d.reject(c):f=new TypeError("invalid state")}catch(h){f=h}ri(d,e,f)}},xi=function(a){a[ji]!==ki&&wi(mi,a)},yi=function(a){return(b,c)=>{c?a.reject(c):a.resolve(b)}},Bi=function(a,b){var c=hi;const d=new qi;a[ti].push({type:si,resolve:null!=c?c:zi,reject:null!=b?b:Ai,complete:yi(d)});xi(a);return d},Di=function(a){if(null===a)return Ci;const b=new qi;b[ji]=ui;b[li]=a;return b},
Ei=function(a){if(a instanceof qi)return a;const b=new qi;a.then(c=>{b.resolve(c)},c=>{b.reject(c)});return b},Fi=function(a){a.prototype.qb=function(){return Ei(this)}},Hi=function(a,b){return Gi(hi(a),function(c){return hi(b.g?b.g(c):b.call(null,c))})},Ii=function(){var a=caches;return a.open.call(a,"v2")},Li=function(a){return Ji.h(Ii(),function(b){return b.addAll.call(b,Ki(a))})},Mi=function(a,b){return Ji.h(Ii(),function(c){return c.put.call(c,a,b)})},Ni=function(a){var b=null!=a?a.request:void 0;
return Hi(Hi(Ji.h(Ji.h(Di(b),fetch),function(c){return Ji.h(Mi(b,c.clone.call(c)),function(){return c})}),function(c){console.log("js/fetch: error",c);c=caches;return c.match.call(c,b)}),function(c){console.error("cache-fetch: failed",c);throw c;})},Ki=function Ki(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return Ki.v(arguments[0],1<c.length?new $APP.D(c.slice(1),0,null):null)};
Ki.v=function(a,b){b=$APP.id(b);var c=$APP.V.i(b,$APP.Bf,$APP.Ge),d=function h(f){if(null==f)return null;if(null!=f?$APP.C===f.Qb||(f.ec?0:$APP.w(ci,f)):$APP.w(ci,f))return di(f);if(f instanceof $APP.X)return c.g?c.g(f):c.call(null,f);if(f instanceof $APP.Kb)return $APP.A.g(f);if($APP.lc(f)){var k={};f=$APP.F(f);for(var l=null,m=0,n=0;;)if(n<m){var p=l.O(null,n),q=$APP.N.i(p,0,null);p=$APP.N.i(p,1,null);q=ei(q,d);p=h(p);k[q]=p;n+=1}else if(f=$APP.F(f))$APP.oc(f)?(m=$APP.tb(f),f=$APP.ub(f),l=m,m=$APP.M(m)):
(m=$APP.G(f),l=$APP.N.i(m,0,null),m=$APP.N.i(m,1,null),l=ei(l,d),m=h(m),k[l]=m,f=$APP.K(f),l=null,m=0),n=0;else break;return k}if(null==f?0:null!=f?f.l&8||$APP.C===f.mc||(f.l?0:$APP.w(bi,f)):$APP.w(bi,f)){k=[];f=$APP.F($APP.Te.h(h,f));l=null;for(n=m=0;;)if(n<m)q=l.O(null,n),k.push(q),n+=1;else if(f=$APP.F(f))l=f,$APP.oc(l)?(f=$APP.tb(l),n=$APP.ub(l),l=f,m=$APP.M(f),f=n):(f=$APP.G(l),k.push(f),f=$APP.K(l),l=null,m=0),n=0;else break;return k}return f};return d(a)};Ki.I=1;
Ki.K=function(a){var b=$APP.G(a);a=$APP.K(a);return this.v(b,a)};var Oi=function(){function a(d,e,f){var h=Gi[$APP.t(null==d?null:d)];if(null!=h)return h.i?h.i(d,e,f):h.call(null,d,e,f);h=Gi._;if(null!=h)return h.i?h.i(d,e,f):h.call(null,d,e,f);throw $APP.z("IPromise.-merr",d);}function b(d,e){var f=Gi[$APP.t(null==d?null:d)];if(null!=f)return f.h?f.h(d,e):f.call(null,d,e);f=Gi._;if(null!=f)return f.h?f.h(d,e):f.call(null,d,e);throw $APP.z("IPromise.-merr",d);}var c=null;c=function(d,e,f){switch(arguments.length){case 2:return b.call(this,d,e);case 3:return a.call(this,
d,e,f)}throw Error("Invalid arity: "+arguments.length);};c.h=b;c.i=a;return c}(),Gi=function Gi(a){switch(arguments.length){case 2:return Gi.h(arguments[0],arguments[1]);case 3:return Gi.i(arguments[0],arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",$APP.A.g(arguments.length)].join(""));}};Gi.h=function(a,b){return null!=a&&null!=a.Fb?a.Fb(a,b):Oi(a,b)};Gi.i=function(a,b,c){return null!=a&&null!=a.Gb?a.Gb(a,b,c):Oi(a,b,c)};Gi.I=3;
var Qi=function(){function a(d,e,f){var h=Pi[$APP.t(null==d?null:d)];if(null!=h)return h.i?h.i(d,e,f):h.call(null,d,e,f);h=Pi._;if(null!=h)return h.i?h.i(d,e,f):h.call(null,d,e,f);throw $APP.z("IPromise.-then",d);}function b(d,e){var f=Pi[$APP.t(null==d?null:d)];if(null!=f)return f.h?f.h(d,e):f.call(null,d,e);f=Pi._;if(null!=f)return f.h?f.h(d,e):f.call(null,d,e);throw $APP.z("IPromise.-then",d);}var c=null;c=function(d,e,f){switch(arguments.length){case 2:return b.call(this,d,e);case 3:return a.call(this,
d,e,f)}throw Error("Invalid arity: "+arguments.length);};c.h=b;c.i=a;return c}(),Pi=function Pi(a){switch(arguments.length){case 2:return Pi.h(arguments[0],arguments[1]);case 3:return Pi.i(arguments[0],arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",$APP.A.g(arguments.length)].join(""));}};Pi.h=function(a,b){return null!=a&&null!=a.Hb?a.Hb(a,b):Qi(a,b)};Pi.i=function(a,b,c){return null!=a&&null!=a.Ib?a.Ib(a,b,c):Qi(a,b,c)};Pi.I=3;var ki=Symbol("state/pending"),ui=Symbol("state/resolved"),vi=Symbol("state/rejected"),ti=Symbol("queue"),ji=Symbol("state"),li=Symbol("value"),pi=Symbol("resolve-type/flatten"),si=Symbol("resolve-type/bind"),oi=Symbol("resolve-type/map"),Ri=a=>a,zi=a=>Di(a),Ai=a=>{throw a;},Si=class extends Error{},qi=class{constructor(a){this[ti]=[];this[ji]=ki;this[li]=void 0;void 0!==a&&ni(this,ui,a)}get state(){return this[ji]}get value(){return this[li]}then(a,b){const c=new qi;this[ti].push({type:pi,resolve:null!=
a?a:Ri,reject:null!=b?b:Ai,complete:yi(c)});xi(this);return c}catch(a){return this.then(null,a)}handle(a,b){let c;b=null!=(c=b)?c:oi;this[ti].push({type:b,resolve:Ri,reject:Ai,complete:a});xi(this)}resolve(a){this[ji]===ki&&ni(this,ui,a);return null}reject(a){this[ji]===ki&&ni(this,vi,a);return null}cancel(){this.reject(new Si("promise cancelled"))}},wi=(()=>{if("function"===typeof $APP.gf.Promise){const a=Promise.resolve(null);return function(b,c){a.then(()=>b(c))}}return"function"===typeof $APP.gf.setImmediate?
$APP.gf.setImmediate:"function"===typeof $APP.gf.setTimeout?(a,b)=>$APP.gf.setTimeout(a,0,b):(a,b)=>a.call(this,b)})(),Ci=new qi(null);Fi(Promise);Fi(qi);$APP.g=qi.prototype;$APP.g.qb=function(){return this};$APP.g.Fb=function(a,b){return Bi(this,function(c){return b.g?b.g(c):b.call(null,c)})};$APP.g.Gb=function(a,b){return Bi(this,function(c){return b.g?b.g(c):b.call(null,c)})};$APP.g.Hb=function(a,b){return this.then(function(c){return b.g?b.g(c):b.call(null,c)})};$APP.g.Ib=function(a,b){return this.then(function(c){return b.g?b.g(c):b.call(null,c)})};$APP.g.Eb=function(){const a=this[li];return this[ji]===vi&&a instanceof Si};
$APP.g.ab=function(){var a=this.value;if($APP.v(this[ji]===vi))throw a;return a};$APP.g.Kb=function(){return this[ji]===vi};$APP.g.Jb=function(){return this[ji]===ki};Error.prototype.qb=function(){const a=new qi;a[ji]=vi;a[li]=this;return a};hi._=function(a){return Di(a)};Promise.prototype.V=$APP.C;Promise.prototype.N=function(a,b){return $APP.lb(b,"#\x3cjs/Promise[~]\x3e")};qi.prototype.V=$APP.C;
qi.prototype.N=function(a,b){return $APP.lb(b,["#\x3cPromise[",$APP.v(gi(this))?"pending":$APP.v(ii(this))?"cancelled":$APP.v(fi(this))?"rejected":"resolved",":",$APP.A.g($APP.Ib(this)),"]\x3e"].join(""))};var Ji=function Ji(a){switch(arguments.length){case 2:return Ji.h(arguments[0],arguments[1]);case 3:return Ji.i(arguments[0],arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",$APP.A.g(arguments.length)].join(""));}};Ji.h=function(a,b){return Pi(hi(a),b)};Ji.i=function(a,b,c){return Pi(hi(a),b,c)};Ji.I=3;console.info("worker: initializing...");var Ti=self;Ti.addEventListener.call(Ti,"activate",function(a){console.info("worker: activate");var b=a.waitUntil,c=b.call;var d=self;d=null!=d?d.registration:void 0;d=null!=d?d.navigationPreload:void 0;d=$APP.v(d)?d.enable.call(d):null;return c.call(b,a,d)});var Ui=self;
Ui.addEventListener.call(Ui,"install",function(a){console.info("worker: install");return a.waitUntil.call(a,Li($APP.rf.h(new $APP.Y(null,5,5,$APP.Bd,["./index.html","./styles.css","./app.js","./shared.js","./favicon.ico"],null),$APP.Te.h(function(b){return["./",$APP.A.g(b)].join("")},$APP.Ff))))});var Vi=self;Vi.addEventListener.call(Vi,"fetch",function(a){return a.respondWith.call(a,Ni(a))});var Wi=self;Wi.addEventListener.call(Wi,"message",function(a){return console.info("worker: message",a)});console.info("worker: init");
}).call(this);