importScripts("shared.js");
(function(){
'use strict';var Ei=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b},Fi=function(){},Gi=function(){},Hi=function(a){if(null!=a&&null!=a.Xb)a=a.Xb(a);else{var b=Hi[$APP.r(null==a?null:a)];if(null!=b)a=b.g?b.g(a):b.call(null,a);else if(b=Hi._,null!=b)a=b.g?b.g(a):b.call(null,a);else throw $APP.y("IEncodeJS.-clj-\x3ejs",a);}return a},Ii=function(a,b){return(null!=a?$APP.C===a.Wb||(a.lc?0:$APP.w(Gi,a)):$APP.w(Gi,a))?Hi(a):"string"===typeof a||"number"===typeof a||a instanceof $APP.W||
a instanceof $APP.Ob?b.g?b.g(a):b.call(null,a):$APP.kf($APP.R([a]),$APP.ya())},Ji=function(a){if(null!=a&&null!=a.Qb)a=a.Qb(a);else{var b=Ji[$APP.r(null==a?null:a)];if(null!=b)a=b.g?b.g(a):b.call(null,a);else if(b=Ji._,null!=b)a=b.g?b.g(a):b.call(null,a);else throw $APP.y("IState.-rejected?",a);}return a},Ki=function(a){if(null!=a&&null!=a.Pb)a=a.Pb(a);else{var b=Ki[$APP.r(null==a?null:a)];if(null!=b)a=b.g?b.g(a):b.call(null,a);else if(b=Ki._,null!=b)a=b.g?b.g(a):b.call(null,a);else throw $APP.y("IState.-pending?",
a);}return a},Li=function(a){if(null!=a&&null!=a.xb)a=a.xb(a);else{var b=Li[$APP.r(null==a?null:a)];if(null!=b)a=b.g?b.g(a):b.call(null,a);else if(b=Li._,null!=b)a=b.g?b.g(a):b.call(null,a);else throw $APP.y("IPromiseFactory.-promise",a);}return a},Mi=function(a){if(null!=a&&null!=a.Kb)a=a.Kb(a);else{var b=Mi[$APP.r(null==a?null:a)];if(null!=b)a=b.g?b.g(a):b.call(null,a);else if(b=Mi._,null!=b)a=b.g?b.g(a):b.call(null,a);else throw $APP.y("ICancellable.-cancelled?",a);}return a},Ri=function(a,b,c){a[Ni]!==
b&&a[Ni]===Oi&&(a[Ni]=b,a[Pi]=c,Qi(a))},Vi=function(a,b,c){c?a.complete(null,c):a.type===Si?a.complete(b,null):a.type===Ti?b instanceof Ui?b.handle((d,e)=>{Vi(a,d,e)}):Ei(b)&&"function"===typeof b.then?b.then(d=>{Vi(a,d,null)},d=>{Vi(a,null,d)}):a.complete(b,null):a.type===Wi?b instanceof Ui?b.handle((d,e)=>{a.complete(d,e)}):Ei(b)&&"function"===typeof b.then?b.then(d=>{a.complete(d,null)},d=>{a.complete(null,d)}):a.complete(null,new TypeError("expected thenable")):a.complete(null,new TypeError("internal: invalid resolve type"))},
Qi=function(a){if(0!==a[Xi].length)for(var b=a[Ni],c=a[Pi],d,e,f;a[Xi].length;){d=a[Xi].shift();try{b===Yi?e=d.resolve(c):b===Zi?e=d.reject(c):f=new TypeError("invalid state")}catch(h){f=h}Vi(d,e,f)}},aj=function(a){a[Ni]!==Oi&&$i(Qi,a)},bj=function(a){return(b,c)=>{c?a.reject(c):a.resolve(b)}},ej=function(a,b){var c=Li;const d=new Ui;a[Xi].push({type:Wi,resolve:null!=c?c:cj,reject:null!=b?b:dj,complete:bj(d)});aj(a);return d},gj=function(a){if(null===a)return fj;const b=new Ui;b[Ni]=Yi;b[Pi]=a;return b},
hj=function(a){if(a instanceof Ui)return a;const b=new Ui;a.then(c=>{b.resolve(c)},c=>{b.reject(c)});return b},ij=function(a){a.prototype.xb=function(){return hj(this)}},kj=function(a,b){return jj(Li(a),function(c){return Li(b.g?b.g(c):b.call(null,c))})},nj=function(a){return lj.h(caches.open("v2"),function(b){return b.addAll(mj(a))})},oj=function(a,b){return lj.h(caches.open("v2"),function(c){return c.put(a,b)})},pj=function(a){var b=$APP.pf(a,"request");return kj(kj(lj.h(lj.h(gj(b),fetch),function(c){return lj.h(oj(b,
c.clone()),function(){return c})}),function(){return caches.match(b)}),function(c){console.log("cache: cache-fetch: cache failed",b,c);throw c;})},mj=function mj(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return mj.s(arguments[0],1<c.length?new $APP.D(c.slice(1),0,null):null)};
mj.s=function(a,b){b=$APP.od(b);var c=$APP.S.i(b,$APP.Of,$APP.Qe),d=function h(f){if(null==f)return null;if(null!=f?$APP.C===f.Wb||(f.lc?0:$APP.w(Gi,f)):$APP.w(Gi,f))return Hi(f);if(f instanceof $APP.W)return c.g?c.g(f):c.call(null,f);if(f instanceof $APP.Ob)return $APP.z.g(f);if($APP.rc(f)){var k={};f=$APP.F(f);for(var l=null,m=0,n=0;;)if(n<m){var p=l.M(null,n),q=$APP.N.i(p,0,null);p=$APP.N.i(p,1,null);q=Ii(q,d);p=h(p);k[q]=p;n+=1}else if(f=$APP.F(f))$APP.uc(f)?(m=$APP.xb(f),f=$APP.yb(f),l=m,m=$APP.M(m)):
(m=$APP.G(f),l=$APP.N.i(m,0,null),m=$APP.N.i(m,1,null),l=Ii(l,d),m=h(m),k[l]=m,f=$APP.J(f),l=null,m=0),n=0;else break;return k}if(null==f?0:null!=f?f.l&8||$APP.C===f.sc||(f.l?0:$APP.w(Fi,f)):$APP.w(Fi,f)){k=[];f=$APP.F($APP.df.h(h,f));l=null;for(n=m=0;;)if(n<m)q=l.M(null,n),k.push(q),n+=1;else if(f=$APP.F(f))l=f,$APP.uc(l)?(f=$APP.xb(l),n=$APP.yb(l),l=f,m=$APP.M(f),f=n):(f=$APP.G(l),k.push(f),f=$APP.J(l),l=null,m=0),n=0;else break;return k}return f};return d(a)};mj.I=1;
mj.K=function(a){var b=$APP.G(a);a=$APP.J(a);return this.s(b,a)};var qj=function(){function a(d,e,f){var h=jj[$APP.r(null==d?null:d)];if(null!=h)return h.i?h.i(d,e,f):h.call(null,d,e,f);h=jj._;if(null!=h)return h.i?h.i(d,e,f):h.call(null,d,e,f);throw $APP.y("IPromise.-merr",d);}function b(d,e){var f=jj[$APP.r(null==d?null:d)];if(null!=f)return f.h?f.h(d,e):f.call(null,d,e);f=jj._;if(null!=f)return f.h?f.h(d,e):f.call(null,d,e);throw $APP.y("IPromise.-merr",d);}var c=null;c=function(d,e,f){switch(arguments.length){case 2:return b.call(this,d,e);case 3:return a.call(this,
d,e,f)}throw Error("Invalid arity: "+arguments.length);};c.h=b;c.i=a;return c}(),jj=function jj(a){switch(arguments.length){case 2:return jj.h(arguments[0],arguments[1]);case 3:return jj.i(arguments[0],arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",$APP.z.g(arguments.length)].join(""));}};jj.h=function(a,b){return null!=a&&null!=a.Lb?a.Lb(a,b):qj(a,b)};jj.i=function(a,b,c){return null!=a&&null!=a.Mb?a.Mb(a,b,c):qj(a,b,c)};jj.I=3;
var sj=function(){function a(d,e,f){var h=rj[$APP.r(null==d?null:d)];if(null!=h)return h.i?h.i(d,e,f):h.call(null,d,e,f);h=rj._;if(null!=h)return h.i?h.i(d,e,f):h.call(null,d,e,f);throw $APP.y("IPromise.-then",d);}function b(d,e){var f=rj[$APP.r(null==d?null:d)];if(null!=f)return f.h?f.h(d,e):f.call(null,d,e);f=rj._;if(null!=f)return f.h?f.h(d,e):f.call(null,d,e);throw $APP.y("IPromise.-then",d);}var c=null;c=function(d,e,f){switch(arguments.length){case 2:return b.call(this,d,e);case 3:return a.call(this,
d,e,f)}throw Error("Invalid arity: "+arguments.length);};c.h=b;c.i=a;return c}(),rj=function rj(a){switch(arguments.length){case 2:return rj.h(arguments[0],arguments[1]);case 3:return rj.i(arguments[0],arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",$APP.z.g(arguments.length)].join(""));}};rj.h=function(a,b){return null!=a&&null!=a.Nb?a.Nb(a,b):sj(a,b)};rj.i=function(a,b,c){return null!=a&&null!=a.Ob?a.Ob(a,b,c):sj(a,b,c)};rj.I=3;var Oi=Symbol("state/pending"),Yi=Symbol("state/resolved"),Zi=Symbol("state/rejected"),Xi=Symbol("queue"),Ni=Symbol("state"),Pi=Symbol("value"),Ti=Symbol("resolve-type/flatten"),Wi=Symbol("resolve-type/bind"),Si=Symbol("resolve-type/map"),tj=a=>a,cj=a=>gj(a),dj=a=>{throw a;},uj=class extends Error{},Ui=class{constructor(a){this[Xi]=[];this[Ni]=Oi;this[Pi]=void 0;void 0!==a&&Ri(this,Yi,a)}get state(){return this[Ni]}get value(){return this[Pi]}then(a,b){const c=new Ui;this[Xi].push({type:Ti,resolve:null!=
a?a:tj,reject:null!=b?b:dj,complete:bj(c)});aj(this);return c}catch(a){return this.then(null,a)}handle(a,b){let c;b=null!=(c=b)?c:Si;this[Xi].push({type:b,resolve:tj,reject:dj,complete:a});aj(this)}resolve(a){this[Ni]===Oi&&Ri(this,Yi,a);return null}reject(a){this[Ni]===Oi&&Ri(this,Zi,a);return null}cancel(){this.reject(new uj("promise cancelled"))}},$i=(()=>{if("function"===typeof $APP.tf.Promise){const a=Promise.resolve(null);return function(b,c){a.then(()=>b(c))}}return"function"===typeof $APP.tf.setImmediate?
$APP.tf.setImmediate:"function"===typeof $APP.tf.setTimeout?(a,b)=>$APP.tf.setTimeout(a,0,b):(a,b)=>a.call(this,b)})(),fj=new Ui(null);ij(Promise);ij(Ui);$APP.g=Ui.prototype;$APP.g.xb=function(){return this};$APP.g.Lb=function(a,b){return ej(this,function(c){return b.g?b.g(c):b.call(null,c)})};$APP.g.Mb=function(a,b){return ej(this,function(c){return b.g?b.g(c):b.call(null,c)})};$APP.g.Nb=function(a,b){return this.then(function(c){return b.g?b.g(c):b.call(null,c)})};$APP.g.Ob=function(a,b){return this.then(function(c){return b.g?b.g(c):b.call(null,c)})};$APP.g.Kb=function(){const a=this[Pi];return this[Ni]===Zi&&a instanceof uj};
$APP.g.ib=function(){var a=this.value;if($APP.v(this[Ni]===Zi))throw a;return a};$APP.g.Qb=function(){return this[Ni]===Zi};$APP.g.Pb=function(){return this[Ni]===Oi};Error.prototype.xb=function(){const a=new Ui;a[Ni]=Zi;a[Pi]=this;return a};Li._=function(a){return gj(a)};Promise.prototype.W=$APP.C;Promise.prototype.N=function(a,b){return $APP.pb(b,"#\x3cjs/Promise[~]\x3e")};Ui.prototype.W=$APP.C;
Ui.prototype.N=function(a,b){return $APP.pb(b,["#\x3cPromise[",$APP.v(Ki(this))?"pending":$APP.v(Mi(this))?"cancelled":$APP.v(Ji(this))?"rejected":"resolved",":",$APP.z.g($APP.Mb(this)),"]\x3e"].join(""))};var lj=function lj(a){switch(arguments.length){case 2:return lj.h(arguments[0],arguments[1]);case 3:return lj.i(arguments[0],arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",$APP.z.g(arguments.length)].join(""));}};lj.h=function(a,b){return rj(Li(a),b)};lj.i=function(a,b,c){return rj(Li(a),b,c)};lj.I=3;console.info("worker: initializing...");self.addEventListener("activate",function(a){console.info("worker: activate");var b=a.waitUntil;var c=$APP.Dc($APP.pf,self,new $APP.X(null,2,5,$APP.Y,["registration","navigationPreload"],null));c=$APP.v(c)?c.enable():null;return b.call(a,c)});
self.addEventListener("install",function(a){console.info("worker: install");return a.waitUntil(nj($APP.Df.h(new $APP.X(null,5,5,$APP.Y,["./index.html","./styles.css","./app.js","./shared.js","./favicon.ico"],null),$APP.df.h(function(b){return["./",$APP.z.g(b)].join("")},$APP.Sf))))});self.addEventListener("fetch",function(a){return a.respondWith(pj(a))});self.addEventListener("message",function(a){return console.info("worker: message",a)});console.info("worker: init");
}).call(this);