importScripts("shared.js");
(function(){
'use strict';var ah=function(){},bh=function(){},ch=function(a){if(null!=a&&null!=a.Ib)a=a.Ib(a);else{var b=ch[$APP.r(null==a?null:a)];if(null!=b)a=b.g?b.g(a):b.call(null,a);else if(b=ch._,null!=b)a=b.g?b.g(a):b.call(null,a);else throw $APP.y("IEncodeJS.-clj-\x3ejs",a);}return a},dh=function(a,b){return(null!=a?$APP.D===a.Hb||(a.Wb?0:$APP.w(bh,a)):$APP.w(bh,a))?ch(a):"string"===typeof a||"number"===typeof a||a instanceof $APP.W||a instanceof $APP.xb?b.g?b.g(a):b.call(null,a):$APP.Je($APP.Q([a]),$APP.na())},
eh=function(){var a=caches;return a.open.call(a,"v1")},gh=function(a){var b=function(){var c=function(){var d=eh();return d.then.call(d,function(e){return e.addAll.call(e,fh(a))})}();return c.then.call(c,function(d){console.log("add-resources-to-cache: addAll success");return d})}();return b["catch"].call(b,function(c){return console.log("add-resources-to-cache: addAll fail",c)})},hh=function(a,b){var c=function(){var d=function(){var e=eh();return e.then.call(e,function(f){return f.put.call(f,a,
b)})}();return d.then.call(d,function(e){console.log("put-in-cache: success");return e})}();return c["catch"].call(c,function(d){return console.log("put-in-cache: fail",d)})},ih=function(a){var b=null!=a?a.request:void 0;a=function(){var c=function(){var d=caches;return d.match.call(d,b)}();return c.then.call(c,function(d){if(null!=d)return d;d=function(){var e=fetch(b);return e.then.call(e,function(f){var h=hh(b,f.clone.call(f));return h.then.call(h,function(){return f})})}();return d["catch"].call(d,
function(e){console.log("js/fetch: error",e);throw e;})})}();return a["catch"].call(a,function(c){console.error("cache-first: failed",c);throw c;})},jh=function jh(a){switch(arguments.length){case 0:return jh.B();case 1:return jh.g(arguments[0]);case 2:return jh.h(arguments[0],arguments[1]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return jh.v(arguments[0],arguments[1],new $APP.F(c.slice(2),0,null))}};
jh.B=function(){return new $APP.zc(null,function(){return null},null)};jh.g=function(a){return new $APP.zc(null,function(){return a},null)};jh.h=function(a,b){return new $APP.zc(null,function(){var c=$APP.G(a);return c?$APP.bc(c)?$APP.Ec($APP.hb(c),jh.h($APP.ib(c),b)):$APP.V($APP.H(c),jh.h($APP.Bb(c),b)):b},null)};
jh.v=function(a,b,c){return function h(e,f){return new $APP.zc(null,function(){var k=$APP.G(e);return k?$APP.bc(k)?$APP.Ec($APP.hb(k),h($APP.ib(k),f)):$APP.V($APP.H(k),h($APP.Bb(k),f)):$APP.v(f)?h($APP.H(f),$APP.J(f)):null},null)}(jh.h(a,b),c)};jh.G=function(a){var b=$APP.H(a),c=$APP.J(a);a=$APP.H(c);c=$APP.J(c);return this.v(b,a,c)};jh.I=2;
var fh=function fh(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return fh.v(arguments[0],1<c.length?new $APP.F(c.slice(1),0,null):null)};
fh.v=function(a,b){b=$APP.Vc(b);var c=$APP.U.j(b,$APP.lf,$APP.pe),d=function h(f){if(null==f)return null;if(null!=f?$APP.D===f.Hb||(f.Wb?0:$APP.w(bh,f)):$APP.w(bh,f))return ch(f);if(f instanceof $APP.W)return c.g?c.g(f):c.call(null,f);if(f instanceof $APP.xb)return $APP.A.g(f);if($APP.Zb(f)){var k={};f=$APP.G(f);for(var l=null,m=0,n=0;;)if(n<m){var p=l.K(null,n),q=$APP.S(p,0,null);p=$APP.S(p,1,null);q=dh(q,d);p=h(p);k[q]=p;n+=1}else if(f=$APP.G(f))$APP.bc(f)?(m=$APP.hb(f),f=$APP.ib(f),l=m,m=$APP.M(m)):
(m=$APP.H(f),l=$APP.S(m,0,null),m=$APP.S(m,1,null),l=dh(l,d),m=h(m),k[l]=m,f=$APP.J(f),l=null,m=0),n=0;else break;return k}if(null==f?0:null!=f?f.l&8||$APP.D===f.cc||(f.l?0:$APP.w(ah,f)):$APP.w(ah,f)){k=[];f=$APP.G($APP.Be.h(h,f));l=null;for(n=m=0;;)if(n<m)q=l.K(null,n),k.push(q),n+=1;else if(f=$APP.G(f))l=f,$APP.bc(l)?(f=$APP.hb(l),n=$APP.ib(l),l=f,m=$APP.M(f),f=n):(f=$APP.H(l),k.push(f),f=$APP.J(l),l=null,m=0),n=0;else break;return k}return f};return d(a)};fh.I=1;
fh.G=function(a){var b=$APP.H(a);a=$APP.J(a);return this.v(b,a)};console.info("worker: initializing...");var kh=self;kh.addEventListener.call(kh,"activate",function(a){console.info("worker: activate");var b=a.waitUntil,c=b.call;var d=self;d=null!=d?d.registration:void 0;d=null!=d?d.navigationPreload:void 0;d=$APP.v(d)?d.enable.call(d):null;return c.call(b,a,d)});var lh=self;
lh.addEventListener.call(lh,"install",function(a){console.info("worker: install");return a.waitUntil.call(a,gh(jh.h(new $APP.X(null,5,5,$APP.Ce,["./index.html","./styles.css","./app.js","./shared.js","./favicon.ico"],null),$APP.Be.h(function(b){return["./",$APP.A.g(b)].join("")},$APP.pf))))});var mh=self;mh.addEventListener.call(mh,"fetch",function(a){return a.respondWith.call(a,ih(a))});var nh=self;nh.addEventListener.call(nh,"message",function(a){return console.info("worker: message",a)});console.info("worker: init");
}).call(this);